#!/usr/bin/env bash

# Script will run ping via the docker image configured for the integration
# Can be used for running unit testing in your favorite editor
#
# Need to configure the editor to have this script on the path
# For example run pycharm from the command line like this:
# PATH=`pwd`/test_data:$PATH charm . &
# Or vscode like this:
# PATH=`pwd`/test_data:$PATH code . &
#

SCRIPT_DIR=$(dirname ${BASH_SOURCE})

DOCKER=$(grep dockerimage $SCRIPT_DIR/../Ping.yml | awk '{print $2}')

docker run --rm -i -v `pwd`:/work "$DOCKER" sh -c "cd /work; ping $*"
