services = [
    {
        "id": 2,
        "shortName": "ids",
        "name": "Security Monitoring",
        "caseTypes": [
            "operationalIncident",
            "change",
            "securityIncident",
            "informational",
        ],
        "workflows": [
            "severityAlert",
            "escalateInfra",
            "escalateTI",
            "escalateDEV",
            "validation",
            "customerUpdate",
            "slaViolation",
            "escalateNSA",
            "escalateLog",
            "internalSlaViolation",
            "escalateMSSAnalyst",
            "escalation",
            "tuning",
        ],
    },
    {
        "id": 6,
        "shortName": "support",
        "name": "Support",
        "caseTypes": ["informational", "operationalIncident"],
        "workflows": ["customerUpdate", "escalateDEV"],
    },
    {
        "id": 13,
        "shortName": "administrative",
        "name": "Administrative",
        "caseTypes": ["informational"],
        "workflows": [
            "escalateTRS",
            "customerUpdate",
            "escalateNSA",
            "escalateInfra",
            "escalateTI",
            "escalateLog",
            "escalateMSSAnalyst",
            "escalateDEV",
        ],
    },
    {
        "id": 221,
        "shortName": "advisory",
        "name": "Advisory",
        "caseTypes": ["informational"],
        "workflows": ["customerUpdate", "escalateMSSAnalyst"],
    },
    {
        "id": 260,
        "shortName": "vulnscan",
        "name": "Vulnerability Scanning",
        "caseTypes": ["informational", "operationalIncident"],
        "workflows": ["escalateTRS", "customerUpdate", "escalateDEV"],
    },
]
