ARGUS_CASE_TAGS = {
    "responseCode": 0,
    "limit": 0,
    "offset": 0,
    "count": 0,
    "size": 0,
    "metaData": {},
    "messages": [
        {
            "message": "string",
            "messageTemplate": "string",
            "type": "FIELD_ERROR",
            "field": "string",
            "parameter": {},
            "timestamp": 0,
        }
    ],
    "data": [
        {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "key": "string",
            "value": "string",
            "addedTimestamp": 0,
            "addedByUser": {
                "id": 0,
                "customerID": 0,
                "customer": {
                    "id": 0,
                    "name": "string",
                    "shortName": "string",
                    "domain": {"id": 0, "name": "string"},
                },
                "domain": {"id": 0, "name": "string"},
                "userName": "string",
                "name": "string",
                "type": "user",
            },
            "flags": ["DELETED"],
            "addedTime": "string",
        }
    ],
}

ARGUS_CASE_COMMENT = {
    "responseCode": 0,
    "limit": 0,
    "offset": 0,
    "count": 0,
    "size": 0,
    "metaData": {},
    "messages": [
        {
            "message": "string",
            "messageTemplate": "string",
            "type": "FIELD_ERROR",
            "field": "string",
            "parameter": {},
            "timestamp": 0,
        }
    ],
    "data": {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "addedTimestamp": 0,
        "addedByUser": {
            "id": 0,
            "customerID": 0,
            "customer": {
                "id": 0,
                "name": "string",
                "shortName": "string",
                "domain": {"id": 0, "name": "string"},
            },
            "domain": {"id": 0, "name": "string"},
            "userName": "string",
            "name": "string",
            "type": "user",
        },
        "comment": "string",
        "flags": ["DELETED"],
        "lastUpdatedTimestamp": 0,
        "status": "pendingCustomer",
        "priority": "low",
        "originEmailAddress": "string",
        "associatedAttachments": [
            {"id": "3fa85f64-5717-4562-b3fc-2c963f66afa6", "name": "string"}
        ],
        "references": [
            {"type": "replacedBy", "commentID": "3fa85f64-5717-4562-b3fc-2c963f66afa6"}
        ],
        "lastUpdatedTime": "string",
        "addedTime": "string",
    },
}

ARGUS_CASE_COMMENTS_LIST = {
    "responseCode": 0,
    "limit": 0,
    "offset": 0,
    "count": 0,
    "size": 0,
    "metaData": {},
    "messages": [
        {
            "message": "string",
            "messageTemplate": "string",
            "type": "FIELD_ERROR",
            "field": "string",
            "parameter": {},
            "timestamp": 0,
        }
    ],
    "data": [
        {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "addedTimestamp": 0,
            "addedByUser": {
                "id": 0,
                "customerID": 0,
                "customer": {
                    "id": 0,
                    "name": "string",
                    "shortName": "string",
                    "domain": {"id": 0, "name": "string"},
                },
                "domain": {"id": 0, "name": "string"},
                "userName": "string",
                "name": "string",
                "type": "user",
            },
            "comment": "string",
            "flags": ["DELETED"],
            "lastUpdatedTimestamp": 0,
            "status": "pendingCustomer",
            "priority": "low",
            "originEmailAddress": "string",
            "associatedAttachments": [
                {"id": "3fa85f64-5717-4562-b3fc-2c963f66afa6", "name": "string"}
            ],
            "references": [
                {
                    "type": "replacedBy",
                    "commentID": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                }
            ],
            "lastUpdatedTime": "string",
            "addedTime": "string",
        }
    ],
}

ARGUS_CASE_METADATA = {
    "responseCode": 0,
    "limit": 0,
    "offset": 0,
    "count": 0,
    "size": 0,
    "metaData": {},
    "messages": [
        {
            "message": "string",
            "messageTemplate": "string",
            "type": "FIELD_ERROR",
            "field": "string",
            "parameter": {},
            "timestamp": 0,
        }
    ],
    "data": {
        "id": 0,
        "customer": {
            "id": 0,
            "name": "string",
            "shortName": "string",
            "domain": {"id": 0, "name": "string"},
        },
        "service": {
            "id": 0,
            "name": "string",
            "shortName": "string",
            "localizedName": "string",
        },
        "category": {
            "id": 0,
            "name": "string",
            "shortName": "string",
            "localizedName": "string",
        },
        "type": "securityIncident",
        "initialStatus": "pendingCustomer",
        "status": "pendingCustomer",
        "initialPriority": "low",
        "priority": "low",
        "subject": "string",
        "description": "string",
        "customerReference": "string",
        "accessMode": "roleBased",
        "reporter": {
            "id": 0,
            "customerID": 0,
            "customer": {
                "id": 0,
                "name": "string",
                "shortName": "string",
                "domain": {"id": 0, "name": "string"},
            },
            "domain": {"id": 0, "name": "string"},
            "userName": "string",
            "name": "string",
            "type": "user",
        },
        "assignedUser": {
            "id": 0,
            "customerID": 0,
            "customer": {
                "id": 0,
                "name": "string",
                "shortName": "string",
                "domain": {"id": 0, "name": "string"},
            },
            "domain": {"id": 0, "name": "string"},
            "userName": "string",
            "name": "string",
            "type": "user",
        },
        "assignedTech": {
            "id": 0,
            "customerID": 0,
            "customer": {
                "id": 0,
                "name": "string",
                "shortName": "string",
                "domain": {"id": 0, "name": "string"},
            },
            "domain": {"id": 0, "name": "string"},
            "userName": "string",
            "name": "string",
            "type": "user",
        },
        "createdTimestamp": 0,
        "createdByUser": {
            "id": 0,
            "customerID": 0,
            "customer": {
                "id": 0,
                "name": "string",
                "shortName": "string",
                "domain": {"id": 0, "name": "string"},
            },
            "domain": {"id": 0, "name": "string"},
            "userName": "string",
            "name": "string",
            "type": "user",
        },
        "lastUpdatedTimestamp": 0,
        "lastUpdatedByUser": {
            "id": 0,
            "customerID": 0,
            "customer": {
                "id": 0,
                "name": "string",
                "shortName": "string",
                "domain": {"id": 0, "name": "string"},
            },
            "domain": {"id": 0, "name": "string"},
            "userName": "string",
            "name": "string",
            "type": "user",
        },
        "closedTimestamp": 0,
        "closedByUser": {
            "id": 0,
            "customerID": 0,
            "customer": {
                "id": 0,
                "name": "string",
                "shortName": "string",
                "domain": {"id": 0, "name": "string"},
            },
            "domain": {"id": 0, "name": "string"},
            "userName": "string",
            "name": "string",
            "type": "user",
        },
        "publishedTimestamp": 0,
        "publishedByUser": {
            "id": 0,
            "customerID": 0,
            "customer": {
                "id": 0,
                "name": "string",
                "shortName": "string",
                "domain": {"id": 0, "name": "string"},
            },
            "domain": {"id": 0, "name": "string"},
            "userName": "string",
            "name": "string",
            "type": "user",
        },
        "flags": ["DELETED"],
        "currentUserAccess": {"level": "read", "role": "user"},
        "workflows": [{"workflow": "validation", "state": "requested"}],
        "originEmailAddress": "string",
        "createdTime": "string",
        "lastUpdatedTime": "string",
        "closedTime": "string",
        "publishedTime": "string",
    },
}

ARGUS_CASE_SEARCH_RESULT = {
    "responseCode": 0,
    "limit": 0,
    "offset": 0,
    "count": 0,
    "size": 0,
    "metaData": {},
    "messages": [
        {
            "message": "string",
            "messageTemplate": "string",
            "type": "FIELD_ERROR",
            "field": "string",
            "parameter": {},
            "timestamp": 0,
        }
    ],
    "data": [
        {
            "id": 0,
            "customer": {
                "id": 0,
                "name": "string",
                "shortName": "string",
                "domain": {"id": 0, "name": "string"},
            },
            "service": {
                "id": 0,
                "name": "string",
                "shortName": "string",
                "localizedName": "string",
            },
            "category": {
                "id": 0,
                "name": "string",
                "shortName": "string",
                "localizedName": "string",
            },
            "type": "securityIncident",
            "initialStatus": "pendingCustomer",
            "status": "pendingCustomer",
            "initialPriority": "low",
            "priority": "low",
            "subject": "string",
            "description": "string",
            "customerReference": "string",
            "accessMode": "roleBased",
            "reporter": {
                "id": 0,
                "customerID": 0,
                "customer": {
                    "id": 0,
                    "name": "string",
                    "shortName": "string",
                    "domain": {"id": 0, "name": "string"},
                },
                "domain": {"id": 0, "name": "string"},
                "userName": "string",
                "name": "string",
                "type": "user",
            },
            "assignedUser": {
                "id": 0,
                "customerID": 0,
                "customer": {
                    "id": 0,
                    "name": "string",
                    "shortName": "string",
                    "domain": {"id": 0, "name": "string"},
                },
                "domain": {"id": 0, "name": "string"},
                "userName": "string",
                "name": "string",
                "type": "user",
            },
            "assignedTech": {
                "id": 0,
                "customerID": 0,
                "customer": {
                    "id": 0,
                    "name": "string",
                    "shortName": "string",
                    "domain": {"id": 0, "name": "string"},
                },
                "domain": {"id": 0, "name": "string"},
                "userName": "string",
                "name": "string",
                "type": "user",
            },
            "createdTimestamp": 0,
            "createdByUser": {
                "id": 0,
                "customerID": 0,
                "customer": {
                    "id": 0,
                    "name": "string",
                    "shortName": "string",
                    "domain": {"id": 0, "name": "string"},
                },
                "domain": {"id": 0, "name": "string"},
                "userName": "string",
                "name": "string",
                "type": "user",
            },
            "lastUpdatedTimestamp": 0,
            "lastUpdatedByUser": {
                "id": 0,
                "customerID": 0,
                "customer": {
                    "id": 0,
                    "name": "string",
                    "shortName": "string",
                    "domain": {"id": 0, "name": "string"},
                },
                "domain": {"id": 0, "name": "string"},
                "userName": "string",
                "name": "string",
                "type": "user",
            },
            "closedTimestamp": 0,
            "closedByUser": {
                "id": 0,
                "customerID": 0,
                "customer": {
                    "id": 0,
                    "name": "string",
                    "shortName": "string",
                    "domain": {"id": 0, "name": "string"},
                },
                "domain": {"id": 0, "name": "string"},
                "userName": "string",
                "name": "string",
                "type": "user",
            },
            "publishedTimestamp": 0,
            "publishedByUser": {
                "id": 0,
                "customerID": 0,
                "customer": {
                    "id": 0,
                    "name": "string",
                    "shortName": "string",
                    "domain": {"id": 0, "name": "string"},
                },
                "domain": {"id": 0, "name": "string"},
                "userName": "string",
                "name": "string",
                "type": "user",
            },
            "flags": ["DELETED"],
            "currentUserAccess": {"level": "read", "role": "user"},
            "workflows": [{"workflow": "validation", "state": "requested"}],
            "originEmailAddress": "string",
            "createdTime": "string",
            "lastUpdatedTime": "string",
            "closedTime": "string",
            "publishedTime": "string",
        }
    ],
}

ARGUS_CASE_ATTACHMENT = {
    "responseCode": 0,
    "limit": 0,
    "offset": 0,
    "count": 0,
    "size": 0,
    "metaData": {},
    "messages": [
        {
            "message": "string",
            "messageTemplate": "string",
            "type": "FIELD_ERROR",
            "field": "string",
            "parameter": {},
            "timestamp": 0,
        }
    ],
    "data": [
        {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "addedTimestamp": 0,
            "addedByUser": {
                "id": 0,
                "customerID": 0,
                "customer": {
                    "id": 0,
                    "name": "string",
                    "shortName": "string",
                    "domain": {"id": 0, "name": "string"},
                },
                "domain": {"id": 0, "name": "string"},
                "userName": "string",
                "name": "string",
                "type": "user",
            },
            "name": "string",
            "mimeType": "string",
            "flags": ["DELETED"],
            "size": 0,
            "originEmailAddress": "string",
            "addedTime": "string",
        }
    ],
}
