# yaml-language-server: $schema=../../../../../schema/handler.schema.json
id: "xsoar-salesforce-iam"

metadata:
  version: "1.0.0"
  description: "XSOAR handler for Salesforce IAM integration"
  module: "xsoar"
  tags:
    - "iam"
    - "identity"
  ownership:
    team: "xsoar"
    maintainers:
      - "@xsoar-content"

enabled: true

triggering:
  type: "PUB_SUB"
  labels:
    xsoar-integration-id: "Salesforce IAM"
    xsoar-pack-id: "Salesforce"
  args: {}

capabilities:
  - id: "automation-and-remediation"
    auth_options:
      - id: "oauth2_client_credentials.salesforce"
        scopes:
        - "api"
        - "chatter_api"
        - "refresh_token"
        - "offline_access"
        workloads:
          - "xsoar-pod"
      - id: "oauth2_authorization_code.salesforce"
        scopes:
        - "api"
        - "chatter_api"
        workloads:
          - "xsoar-pod"

test_connection:
  type: "service"
  service: "xsoar"
  endpoint: "/settings/integration/connector/verification"