id: Vega Alert - External IP Enrichment - Generic
version: 10
vcShouldKeepItemLegacyProdMachine: false
name: Vega Alert - External IP Enrichment - Generic
fromversion: 6.10.0
description: Enriches incoming IP addresses using the 'IP Enrichment - External -
  Generic v2' sub-playbook and automatically posts the retrieved endpoint details
  back to the Vega Alert as a comment.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 1fd6c57a-a639-4545-8a11-50c518eb6728
    type: start
    task:
      id: 1fd6c57a-a639-4545-8a11-50c518eb6728
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 9c568987-50b1-490d-83ad-d3243166bab0
    type: playbook
    task:
      id: 9c568987-50b1-490d-83ad-d3243166bab0
      version: -1
      name: IP Enrichment - External - Generic v2
      playbookName: IP Enrichment - External - Generic v2
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: aa2793d2-0ba8-4c46-b547-24beb1eb026d
    type: regular
    task:
      id: aa2793d2-0ba8-4c46-b547-24beb1eb026d
      version: -1
      name: vega-update-alert
      description: Immediately update Vega alert status, severity, verdict, verdict
        reasoning, assignees, and/or comment on the Vega platform and sync the open
        XSOAR investigation when run from a Vega Alert investigation.
      script: Vega|||vega-update-alert
      type: regular
      iscommand: true
      brand: Vega
    scriptarguments:
      alert_ids:
        complex:
          root: incident
          accessor: externallink
          transformers:
          - operator: split
            args:
              delimiter:
                value:
                  simple: /
          - operator: atIndex
            args:
              index:
                value:
                  simple: "6"
      comment:
        simple: ${Endpoint}${DBotScore}${IP}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 375
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 400,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
