description: Starts Instant VM Recovery with manual configuration.
id: Veeam - Start Instant VM Recovery Manually
inputs:
- description: ""
  key: Instance
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: sourceInstance
      root: incident
- description: ""
  key: backupObjectId
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: veeambackupobjectid
      root: incident
name: Veeam - Start Instant VM Recovery Manually
outputs: []
starttaskid: "0"
fromversion: "6.10.0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e31a85d9-05fd-4de6-87b2-c1cf4da20056
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: e31a85d9-05fd-4de6-87b2-c1cf4da20056
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 40,
          "y": -510
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      limit:
        simple: "1"
      malwareStatusFilter:
        simple: Clean
      nameFilter:
        complex:
          accessor: name
          root: Veeam.VBR.backup_object
      orderAsc:
        simple: "false"
      orderColumn:
        simple: CreationTime
      platformNameFilter:
        simple: VMware
      using:
        complex:
          root: inputs.Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: VBR REST API
      description: Get all clean restore points (without detected malware activity).
      id: b3e2e312-08d6-4b51-8c99-c85328fa9f00
      iscommand: true
      name: Get All Restore Points
      script: VBR REST API|||veeam-vbr-get-restore-points
      type: regular
      version: -1
    taskid: b3e2e312-08d6-4b51-8c99-c85328fa9f00
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 40,
          "y": 20
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      antivirusScanEnabled:
        complex:
          accessor: "0"
          root: Specify Parameters for Instant VM Recovery.Answers
      biosUuidPolicy:
        simple: preserve
      folderObjectId:
        complex:
          accessor: "1"
          root: Specify Parameters for Instant VM Recovery.Answers
      hostObjectId:
        complex:
          accessor: "2"
          root: Specify Parameters for Instant VM Recovery.Answers
      overwrite:
        simple: "false"
      platform:
        complex:
          accessor: "3"
          root: Specify Parameters for Instant VM Recovery.Answers
      redirectEnabled:
        simple: "false"
      restorePointId:
        complex:
          accessor: id
          root: Veeam.VBR.get_restore_points.data
      restoredVmName:
        complex:
          accessor: restored_vm_name
          root: Veeam.VMNAME
      using:
        complex:
          root: inputs.Instance
      vCenterName:
        complex:
          accessor: "4"
          root: Specify Parameters for Instant VM Recovery.Answers
    separatecontext: false
    skipunavailable: false
    task:
      brand: VBR REST API
      description: Start Customized VM Instant Recovery.
      id: 547c6260-6ae1-4365-883c-b0d9cc9c6f50
      iscommand: true
      name: Start Customized VM Instant Recovery
      script: VBR REST API|||veeam-vbr-start-instant-recovery-customized
      type: regular
      version: -1
    taskid: 547c6260-6ae1-4365-883c-b0d9cc9c6f50
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -490,
          "y": 780
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 75c4cd93-9c68-4c70-8296-f208b22d6367
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 75c4cd93-9c68-4c70-8296-f208b22d6367
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 40,
          "y": 2130
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      id_:
        complex:
          root: inputs.backupObjectId
      using:
        complex:
          root: inputs.Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: VBR REST API
      description: Get Backup Object.
      id: fd93bcc9-d09e-49b8-89ad-7ebd47ceec81
      iscommand: true
      name: Get Backup Object
      script: VBR REST API|||veeam-vbr-get-backup-object
      type: regular
      version: -1
    taskid: fd93bcc9-d09e-49b8-89ad-7ebd47ceec81
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 40,
          "y": -170
        }
      }
  "12":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: id
                root: Veeam.VBR.get_restore_points.data
          operator: isNotEmpty
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "22"
      "yes":
      - "27"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check Restore Point Existence.
      id: 42d9f6a4-1de8-4bb8-8a89-f471d378b154
      iscommand: false
      name: Check Restore Point Existence
      type: condition
      version: -1
    taskid: 42d9f6a4-1de8-4bb8-8a89-f471d378b154
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 40,
          "y": 210
        }
      }
  "15":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: state
                root: Veeam.VBR.get_session
          operator: isEqualString
          right:
            value:
              simple: Working
      label: "yes"
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "17"
      "yes":
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check Session State.
      id: 385e2697-98b1-4c9d-8507-8ea5c8c60bad
      iscommand: false
      name: Check Session State
      type: condition
      version: -1
    taskid: 385e2697-98b1-4c9d-8507-8ea5c8c60bad
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -490,
          "y": 1290
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c265fe79-de44-4696-8e6a-776a882f54fd
      iscommand: false
      name: Success
      type: title
      version: -1
      description: ''
    taskid: c265fe79-de44-4696-8e6a-776a882f54fd
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -220,
          "y": 1510
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      Finish:
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Instant VM Recovery has not been completed.
      id: 94a53950-2dcb-47e4-81e8-9414dcc5d2d5
      iscommand: false
      name: Failed
      type: condition
      version: -1
    taskid: 94a53950-2dcb-47e4-81e8-9414dcc5d2d5
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -670,
          "y": 1700
        }
      }
  "20":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: antivirusScanEnabled
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: If `true`, Veeam Backup & Replication scans machine data with antivirus
          software before restoring the machine to the production environment.
        type: shortText
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "1"
        label: ""
        labelarg:
          simple: folderObjectId
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: ID of the VMware vSphere object. The parameter is required for all
          VMware vSphere objects except vCenter Servers and standalone ESXi hosts.
        type: shortText
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "2"
        label: ""
        labelarg:
          simple: hostObjectId
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: ID of the VMware vSphere object. The parameter is required for all
          VMware vSphere objects except vCenter Servers and standalone ESXi hosts.
        type: shortText
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "3"
        label: ""
        labelarg:
          simple: platform
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: Platform name.
        type: shortText
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "4"
        label: ""
        labelarg:
          simple: vCenterName
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: Name of the vCenter Server.
        type: shortText
      sender: Your SOC team
      title: Specify Parameters for Instant VM Recovery
      totalanswers: 0
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body: null
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Enter Parameters.
      id: a8eaaaeb-156a-40c9-8d41-66946bdbd25e
      iscommand: false
      name: Specify Parameters for Instant VM Recovery
      type: collection
      version: -1
    taskid: a8eaaaeb-156a-40c9-8d41-66946bdbd25e
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": -490,
          "y": 585
        }
      }
  "21":
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      OK:
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Go to the Veeam Backup & Replication console to finish the migration
        process.
      id: 66d7c7fc-3ef3-4967-8d44-6adcb0d9e0f8
      iscommand: false
      name: Finish Migration
      type: condition
      version: -1
    taskid: 66d7c7fc-3ef3-4967-8d44-6adcb0d9e0f8
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -210,
          "y": 1700
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: No Clean Restore Points Found
      cc: null
      format: ""
      methods: []
      replyOptions:
      - Finish
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      Finish:
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: No Clean Restore Points Found.
      id: 11ec3202-c196-4d77-8388-991aa2fefc28
      iscommand: false
      name: No Clean Restore Points Found
      type: condition
      version: -1
    taskid: 11ec3202-c196-4d77-8388-991aa2fefc28
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 40,
          "y": 640
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Delete field from context.\n\nThis automation runs using the default
        Limited User role, unless you explicitly change the permissions.\nFor more
        information, see the section about permissions here:\n- For Cortex XSOAR 6
        see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      id: ff1fff27-a54d-4d3f-83cd-cd73dec6093b
      iscommand: false
      name: Clear Context Data
      script: DeleteContext
      type: regular
      version: -1
    taskid: ff1fff27-a54d-4d3f-83cd-cd73dec6093b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 40,
          "y": -350
        }
      }
  "25":
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: using
      AdditionalPollingCommandArgValues:
        complex:
          root: inputs.Instance
      Ids:
        complex:
          accessor: id
          root: Veeam.VBR.start_recovery
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: id_
      PollingCommandName:
        simple: veeam-vbr-get-session
      Timeout:
        simple: "30"
      dt:
        simple: Veeam.VBR.get_session(val.state != 'Stopped' && val.state != 'Working').id
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 9b561688-7c26-4288-84b4-55a8b1d1c548
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 9b561688-7c26-4288-84b4-55a8b1d1c548
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -490,
          "y": 950
        }
      }
  "26":
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      id_:
        complex:
          accessor: id
          root: Veeam.VBR.start_recovery
      using:
        complex:
          root: inputs.Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: VBR REST API
      description: Get Session.
      id: 3f13f12e-b19c-4dd0-8b78-89394edd2337
      iscommand: true
      name: Get Session
      script: VBR REST API|||veeam-vbr-get-session
      type: regular
      version: -1
    taskid: 3f13f12e-b19c-4dd0-8b78-89394edd2337
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -490,
          "y": 1110
        }
      }
  "27":
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      VmName:
        complex:
          accessor: name
          root: Veeam.VBR.backup_object
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get Restored VM Name.
      id: 8765d542-515e-4cf8-8a01-32c4beedf345
      iscommand: false
      name: Get Restored VM Name
      script: GetRestoredVmName
      type: regular
      version: -1
    taskid: 8765d542-515e-4cf8-8a01-32c4beedf345
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -490,
          "y": 400
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2705,
        "width": 1090,
        "x": -670,
        "y": -510
      }
    }
  }
