description: Starts a Quick Backup session for a specific virtual machine.
id: Veeam - Start Quick Backup
inputs:
- description: ""
  key: Instance
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: sourceInstance
      root: incident
- description: ""
  key: backupObjectId
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: veeambackupobjectid
      root: incident
name: Veeam - Start Quick Backup
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8120bc05-1f34-492c-8199-755b60845037
      iscommand: false
      name: ""
      version: -1
    taskid: 8120bc05-1f34-492c-8199-755b60845037
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 700,
          "y": -150
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: true
    quietmode: 0
    scriptarguments:
      hostName:
        complex:
          accessor: vcenter_name
          root: Veeam.VBR.backup_object
      name:
        complex:
          accessor: name
          root: Veeam.VBR.backup_object
      objectId:
        complex:
          accessor: objectId
          root: Veeam.VBR.backup_object
      platform:
        complex:
          accessor: platformName
          root: Veeam.VBR.backup_object
      type:
        complex:
          accessor: viType
          root: Veeam.VBR.backup_object
      using:
        complex:
          root: inputs.Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: VBR REST API
      description: Starts a Quick Backup session for a VMware vSphere VM.
      id: 07c7e1d9-7b55-4465-8c63-f465a9d3b61d
      iscommand: true
      name: Start Quick Backup
      script: VBR REST API|||veeam-vbr-start-vsphere-quick-backup
      type: regular
      version: -1
    taskid: 07c7e1d9-7b55-4465-8c63-f465a9d3b61d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 400,
          "y": 500
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: b70cb99e-c619-44fd-83be-c86ca6cb3e82
      iscommand: false
      name: Clear Context Data
      script: DeleteContext
      type: regular
      version: -1
    taskid: b70cb99e-c619-44fd-83be-c86ca6cb3e82
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 700,
          "y": -10
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      id_:
        complex:
          root: inputs.backupObjectId
      using:
        complex:
          root: inputs.Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: VBR REST API
      description: Gets a backup object.
      id: 99c415c8-307d-4858-857e-fce4f508e40b
      iscommand: true
      name: Get Backup Object
      script: VBR REST API|||veeam-vbr-get-backup-object
      type: regular
      version: -1
    taskid: 99c415c8-307d-4858-857e-fce4f508e40b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 710,
          "y": 120
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5da54d8c-7fa1-438f-8c9d-64b8dae6a06f
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 5da54d8c-7fa1-438f-8c9d-64b8dae6a06f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 700,
          "y": 1570
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: using
      AdditionalPollingCommandArgValues:
        complex:
          root: inputs.Instance
      Ids:
        complex:
          accessor: id
          root: Veeam.VBR.start_vsphere_quick_backup
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: id_
      PollingCommandName:
        simple: veeam-vbr-get-session
      Timeout:
        simple: "120"
      dt:
        simple: Veeam.VBR.get_session(val.state != 'Stopped').id
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 67f9b39a-3bc2-4647-86ba-d68f36b454d6
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 67f9b39a-3bc2-4647-86ba-d68f36b454d6
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 700,
          "y": 680
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: true
    quietmode: 2
    scriptarguments:
      id_:
        complex:
          accessor: id
          root: Veeam.VBR.start_vsphere_quick_backup
      using:
        complex:
          root: inputs.Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: VBR REST API
      description: Gets session data.
      id: 92b6839e-ecf0-4288-8bdf-cb4de37a5389
      iscommand: true
      name: Get Session
      script: VBR REST API|||veeam-vbr-get-session
      type: regular
      version: -1
    taskid: 92b6839e-ecf0-4288-8bdf-cb4de37a5389
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 700,
          "y": 850
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: result
                root: Veeam.VBR.get_session.result
          operator: isEqualString
          right:
            value:
              simple: Success
        - left:
            iscontext: true
            value:
              complex:
                accessor: result
                root: Veeam.VBR.get_session.result
          operator: isEqualString
          right:
            value:
              simple: Warning
      label: "yes"
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b79115df-d05a-4f62-8e26-85a6b3814f2d
      iscommand: false
      name: Check Session State
      type: condition
      version: -1
    taskid: b79115df-d05a-4f62-8e26-85a6b3814f2d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 700,
          "y": 1010
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: dc01ab55-ad6e-44a2-88c0-4ebb079e4d3e
      iscommand: false
      name: Success
      type: title
      version: -1
    taskid: dc01ab55-ad6e-44a2-88c0-4ebb079e4d3e
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 700,
          "y": 1240
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      Finish:
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns an error if a Quick Backup session has not been completed.
      id: 417f2555-c76c-4764-84e0-e9405db40045
      iscommand: false
      name: Failed
      type: condition
      version: -1
    taskid: 417f2555-c76c-4764-84e0-e9405db40045
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 190,
          "y": 1290
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: true
    quietmode: 0
    scriptarguments:
      hostName:
        complex:
          accessor: vcenter_name
          root: Veeam.VBR.backup_object
      name:
        complex:
          accessor: name
          root: Veeam.VBR.backup_object
      objectId:
        complex:
          accessor: objectId
          root: Veeam.VBR.backup_object
      platform:
        simple: VSphere
      type:
        complex:
          accessor: viType
          root: Veeam.VBR.backup_object
      using:
        complex:
          root: inputs.Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: VBR REST API
      description: Start a Quick Backup session for a VMware vSphere VM.
      id: 5389c390-85ba-491f-80af-9f932dfa58a0
      iscommand: true
      name: Start Quick Backup
      script: VBR REST API|||veeam-vbr-start-vsphere-quick-backup
      type: regular
      version: -1
    taskid: 5389c390-85ba-491f-80af-9f932dfa58a0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 930,
          "y": 490
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: lastRunFailed
                root: Veeam.VBR.backup_object
          operator: isNotExists
      label: "yes"
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5768e58d-8b14-4a44-8659-c03c2142a56c
      iscommand: false
      name: Check Last Run Failed
      type: condition
      version: -1
    taskid: 5768e58d-8b14-4a44-8659-c03c2142a56c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 700,
          "y": 280
        }
      }
version: -1
fromversion: 6.10.0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1785,
        "width": 1120,
        "x": 190,
        "y": -150
      }
    }
  }
