description: Stops an active disk publishing session.
id: Veeam - Stop Disk Publishing
inputs:
- description: ""
  key: Instance
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: mountId
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: ""
  playbookInputQuery:
    daterange:
      fromdate: "0001-01-01T00:00:00Z"
      fromdatelicenseval: "0001-01-01T00:00:00Z"
      period:
        by: ""
        byfrom: ""
        byto: ""
        field: ""
        fromvalue: null
        tovalue: null
      todate: "0001-01-01T00:00:00Z"
    query: ""
    queryEntity: indicators
    results: null
    runFromLastJobTime: true
  required: false
  value: {}
name: Veeam - Stop Disk Publishing
outputs: []
quiet: true
sourceplaybookid: Veeam - Start Scan Backup
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 653c1677-bb20-45e8-89b3-f2badfc2c986
      iscommand: false
      name: ""
      version: -1
    taskid: 653c1677-bb20-45e8-89b3-f2badfc2c986
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: 9f3c430e-405d-4884-8630-1822ba7bf006
      iscommand: false
      name: |
        Clear Context Data
      script: DeleteContext
      type: regular
      version: -1
    taskid: 9f3c430e-405d-4884-8630-1822ba7bf006
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: using
      AdditionalPollingCommandArgValues:
        complex:
          root: inputs.Instance
      Ids:
        complex:
          root: inputs.mountId
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: id_
      PollingCommandName:
        simple: veeam-vbr-get-session
      Timeout:
        simple: "120"
      dt:
        simple: Veeam.VBR.get_session(val.state != 'Stopped').id
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 169916a6-e9bf-49ae-8231-be99b5270fac
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 169916a6-e9bf-49ae-8231-be99b5270fac
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      id_:
        complex:
          root: inputs.mountId
      using:
        complex:
          root: inputs.Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: VBR REST API
      description: Gets session data.
      id: 3601d920-0582-4a25-8e17-e41f8627d0d7
      iscommand: true
      name: Get Session
      script: VBR REST API|||veeam-vbr-get-session
      type: regular
      version: -1
    taskid: 3601d920-0582-4a25-8e17-e41f8627d0d7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "20":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: result
                root: Veeam.VBR.get_session.result
          operator: isEqualString
          right:
            value:
              simple: Success
        - left:
            iscontext: true
            value:
              complex:
                accessor: result
                root: Veeam.VBR.get_session.result
          operator: isEqualString
          right:
            value:
              simple: Warning
      label: "yes"
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "22"
      "yes":
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c46beaa4-2644-4553-88f4-95cc9dfb8b10
      iscommand: false
      name: Check Session State
      type: condition
      version: -1
    taskid: c46beaa4-2644-4553-88f4-95cc9dfb8b10
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      Finish:
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns an error if disk publishing cannot be stopped.
      id: 3752ba3d-6a0b-4ca1-8e74-6afe68006f25
      iscommand: false
      name: Failed
      type: condition
      version: -1
    taskid: 3752ba3d-6a0b-4ca1-8e74-6afe68006f25
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b8cecbac-ba01-4496-80ed-5b8fef35bda3
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: b8cecbac-ba01-4496-80ed-5b8fef35bda3
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1245
        }
      }
  "26":
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f4039a23-6095-4557-8960-d0fcc9e20821
      iscommand: false
      name: Success
      type: title
      version: -1
    taskid: f4039a23-6095-4557-8960-d0fcc9e20821
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1085
        }
      }
  "28":
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      mountId:
        complex:
          root: inputs.mountId
      using:
        complex:
          root: inputs.Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: VBR REST API
      description: Stops publishing of disk content and unmounts published disks.
      id: 16975cd6-5e29-4398-89e4-a8f7cc598232
      iscommand: true
      name: Stop Disk Publishing
      script: VBR REST API|||veeam-vbr-stop-disk-publishing
      type: regular
      version: -1
    taskid: 16975cd6-5e29-4398-89e4-a8f7cc598232
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
version: -1
fromversion: 6.10.0
view: |-
  {
    "linkLabelsPosition": {
      "22_23_Finish": 0.46
    },
    "paper": {
      "dimensions": {
        "height": 1260,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
