description: Resolves Veeam ONE triggered alarms.
id: Veeam - Resolve Triggered Alarms
inputs:
- description: ""
  key: TriggeredAlarmId
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: eventid
      root: incident
- description: ""
  key: Instance
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: sourceInstance
      root: incident
name: Veeam - Resolve Triggered Alarms
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1c5f0daf-635d-4834-8383-200c4b607c9e
      iscommand: false
      name: ""
      version: -1
    taskid: 1c5f0daf-635d-4834-8383-200c4b607c9e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 20
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      comment:
        complex:
          root: incident.owner
          transformers:
          - args:
              prefix:
                value:
                  simple: 'Resolved by Cortex XSOAR user: '
              suffix: {}
            operator: concat
      resolveType:
        simple: Resolve
      triggeredAlarmIds:
        complex:
          root: inputs.TriggeredAlarmId
          transformers:
          - operator: StringToArray
      using:
        complex:
          root: inputs.Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Veeam ONE REST API
      description: Resolve Triggered Alarms
      id: 2fb50d10-d29f-4d71-8e30-32f53870c58e
      iscommand: true
      name: Resolve Triggered Alarms
      script: Veeam ONE REST API|||veeam-vone-resolve-triggered-alarms
      type: regular
      version: -1
    taskid: 2fb50d10-d29f-4d71-8e30-32f53870c58e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 150,
          "y": 440
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      comment:
        complex:
          root: incident.owner
          transformers:
          - args:
              prefix:
                value:
                  simple: 'Acknowledged by Cortex XSOAR user: '
              suffix: {}
            operator: concat
      resolveType:
        simple: Acknowledge
      triggeredAlarmIds:
        complex:
          root: inputs.TriggeredAlarmId
          transformers:
          - operator: StringToArray
      using:
        complex:
          root: inputs.Instance
    separatecontext: false
    skipunavailable: false
    task:
      brand: Veeam ONE REST API
      description: Resolve Triggered Alarms
      id: c9a949d2-c1bf-4f10-8e68-72917feb697c
      iscommand: true
      name: Resolve Triggered Alarms
      script: Veeam ONE REST API|||veeam-vone-resolve-triggered-alarms
      type: regular
      version: -1
    taskid: c9a949d2-c1bf-4f10-8e68-72917feb697c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 730,
          "y": 440
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      Acknowledge:
      - "2"
      Resolve:
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Select Alarm Resolution Type
      id: 19dc1a79-6377-4934-81c9-e03b5c2b40a7
      iscommand: false
      name: Select Alarm Resolution Type
      type: condition
      version: -1
    taskid: 19dc1a79-6377-4934-81c9-e03b5c2b40a7
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: fe4a6f6e-af0d-4d51-8651-64d5d6bb5c32
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: fe4a6f6e-af0d-4d51-8651-64d5d6bb5c32
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 160,
          "y": 710
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6399b1bd-2496-4b67-88fa-3e3f2eeb332c
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 6399b1bd-2496-4b67-88fa-3e3f2eeb332c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 890
        }
      }
version: -1
fromversion: 6.10.0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 935,
        "width": 960,
        "x": 150,
        "y": 20
      }
    }
  }
