id: Get Original Email - Microsoft Graph Mail - test
version: -1
vcShouldKeepItemLegacyProdMachine: false
name: Get Original Email - Microsoft Graph Mail - test
description: '"Get Original Email - Microsoft Graph Mail" test playbook.'
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 42ff3e7a-e0bd-4153-8e4d-2ee6ff01bf94
    type: start
    task:
      id: 42ff3e7a-e0bd-4153-8e4d-2ee6ff01bf94
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: fd60bf2f-b882-41b4-a945-7f20db36644c
    type: condition
    task:
      id: fd60bf2f-b882-41b4-a945-7f20db36644c
      version: -1
      name: Check output
      description: Check the playbook outputs.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: greaterThan
          left:
            value:
              complex:
                root: File
                accessor: Size
                transformers:
                - operator: FirstArrayElement
            iscontext: true
          right:
            value:
              simple: "0"
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 910ac6fe-9e3a-4a22-87d3-511b3ef3c28e
    type: regular
    task:
      id: 910ac6fe-9e3a-4a22-87d3-511b3ef3c28e
      version: -1
      name: Print success
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      value:
        simple: SUCCESS
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 680,
          "y": 570
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 81ab59a5-3b92-4a0d-86c7-90cdd294e9b9
    type: regular
    task:
      id: 81ab59a5-3b92-4a0d-86c7-90cdd294e9b9
      version: -1
      name: Print Error
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: ERROR
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 220,
          "y": 570
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: e744eaba-ce88-4873-b6f2-4602e25ff6ad
    type: playbook
    task:
      id: e744eaba-ce88-4873-b6f2-4602e25ff6ad
      version: -1
      name: Get Original Email - Microsoft Graph Mail
      description: |-
        This playbook retrieves the original email using the Microsoft Graph Mail integration.
        Note: You must have the necessary permissions in the Microsoft Graph Mail integration as described in the [message-get API](https://docs.microsoft.com/en-us/graph/api/message-get) and the [user-list-messages API](https://docs.microsoft.com/en-us/graph/api/user-list-messages)
      playbookName: Get Original Email - Microsoft Graph Mail
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      MessageID:
        complex:
          root: MSGraphMail
          accessor: InternetMessageID
          transformers:
          - operator: FirstArrayElement
      PagesToPull:
        simple: "10"
      UserID:
        simple: avishai@demistodev.onmicrosoft.com
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: ba8a73cd-7d44-496c-ba58-9434aa68ad61
    type: regular
    task:
      id: ba8a73cd-7d44-496c-ba58-9434aa68ad61
      version: -1
      name: Get one Email
      description: Gets the properties of returned emails. Typically shows partial
        results, use the "page_size" and "pages_to_pull" arguments to get all results.
      script: MicrosoftGraphMail|||msgraph-mail-list-emails
      type: regular
      iscommand: true
      brand: MicrosoftGraphMail
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      page_size:
        simple: "1"
      user_id:
        simple: avishai@demistodev.onmicrosoft.com
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 25
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 755,
        "width": 840,
        "x": 220,
        "y": -110
      }
    }
  }
inputs:
- key: UserID
  value:
    simple: avishai@demistodev.onmicrosoft.com
  required: false
  description: ""
  playbookInputQuery: null
- key: MessageID
  value:
    simple: <VI1PR07MB6656AF1CC691E69D7FB0AD2F99859@VI1PR07MB6656.eurprd07.prod.outlook.com>
  required: false
  description: ""
  playbookInputQuery: null
- key: EmailSubject
  value:
    simple: TEST_EMAIL_DO_NOT_DELETE
  required: false
  description: ""
  playbookInputQuery: null
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.1.0
