# noqa: F401
from flask import Flask, jsonify
from gevent.pywsgi import WSGIServer
from CommonServerPython import *

FIRST_RUN_REPORT = {
    "Report_Entry": [
        {
            "Employee_Type": "Regular",
            "Leadership": "Yes-HQ",
            "Work_Country_Code": "840",
            "Street_Address": "3000 Tannery Way",
            "Employment_Status": "Active",
            "VP_Flag": "N",
            "Mgr_ID": "115069",
            "Cost_Center_Description": "Channel Sales",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "Y",
            "Email_-_Primary_Home": "ronnyrahardjo@test.com",
            "First_Name": "Ronny",
            "Last_Hire_Date": "10/05/2020",
            "People_Manager_Flag": "N",
            "Department": "Sales NAM:NAM Channel Sales",
            "Workday_ID": "5aa443c785ff10461ac83e5a6be32e1e",
            "Postal_Code": "95054",
            "Rehired_Employee": "Yes",
            "Org_Level_1": "Sales",
            "Org_Level_3": "NAM Channel Sales",
            "Country_Name": "United States Of America",
            "Org_Level_2": "Sales NAM",
            "Emp_ID": "100122",
            "Job_Family": "Product Management",
            "User_Name": "rrahardjo@test.com",
            "Preferred_Name_-_First_Name": "Ronny",
            "Prehire_Flag": "False",
            "Management_Level_1": "Nikesh Arora",
            "Work_Country_Abbrev": "US",
            "Management_Level_2": "Timmy Turner",
            "Email_Address": "rrahardjo@test.com",
            "Title": "Dir, Product Line Manager",
            "City": "Santa Clara",
            "Work_State_US_Only": "California",
            "Job_Code": "2245",
            "PAN_CF_Okta_Location_Region": "Americas",
            "Last_Name": "Rahardjo",
            "Job_Function": "Product Management Function",
            "State": "California",
            "Exec_Admin_Flag": "N",
            "Preferred_Name": "Ronny Rahardjo",
            "Regular_Employee_Flag": "Y",
            "Preferred_Name_-_Last_Name": "Rahardjo",
            "Cost_Center_Code": "120100",
            "Location": "Office - USA - CA - Headquarters"
        },
        {
            "Employee_Type": "Regular",
            "Leadership": "No",
            "Work_Country_Code": "840",
            "Street_Address": "WeWork Embarcadero Center",
            "Employment_Status": "Active",
            "VP_Flag": "N",
            "Mgr_ID": "115069",
            "Cost_Center_Description": "Magnifier Sales Inc",
            "GDPR_Country_Flag": "0",
            "Public_Work_Mobile_Phone_Number": "+44  7900-160-819",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "stevearnoldtstc@test.com",
            "First_Name": "Stephen",
            "Last_Hire_Date": "10/01/2020",
            "People_Manager_Flag": "N",
            "Department": "WW Sales Functions:Cortex Sales",
            "Workday_ID": "5aa443c785ff10461a941c31a173e459",
            "Postal_Code": "94111",
            "Rehired_Employee": "Yes",
            "Org_Level_1": "Sales",
            "Org_Level_3": "Cortex Sales",
            "Country_Name": "United States Of America",
            "Org_Level_2": "WW Sales Functions",
            "Emp_ID": "101351",
            "Job_Family": "Software Engineering",
            "User_Name": "sarnold@test.com",
            "Preferred_Name_-_First_Name": "Stephen",
            "Prehire_Flag": "False",
            "Management_Level_1": "Nikesh Arora",
            "Work_Country_Abbrev": "US",
            "Management_Level_2": "Timmy Turner",
            "Email_Address": "sarnold@test.com",
            "Title": "Mgr, SW Engineering",
            "City": "San Francisco",
            "Work_State_US_Only": "California",
            "Job_Code": "2163",
            "PAN_CF_Okta_Location_Region": "Americas",
            "Last_Name": "Arnold",
            "Job_Function": "Engineering Function",
            "State": "California",
            "Exec_Admin_Flag": "N",
            "Preferred_Name": "Stephen Arnold",
            "Regular_Employee_Flag": "Y",
            "Preferred_Name_-_Last_Name": "Arnold",
            "Cost_Center_Code": "101100",
            "Location": "Office - USA - CA - San Francisco"
        },
        {
            "Employee_Type": "Regular",
            "Leadership": "No",
            "Work_Country_Code": "840",
            "Street_Address": "3000 Tannery Way",
            "Employment_Status": "Active",
            "VP_Flag": "N",
            "Mgr_ID": "115069",
            "Cost_Center_Description": "IoT - Engineering",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "test37@testing.com",
            "First_Name": "Tooth",
            "Last_Hire_Date": "06/15/2020",
            "People_Manager_Flag": "N",
            "Department": "Enterprise R&D:FWaaP",
            "Workday_ID": "9aa7e309929e01ebec7923080803461b",
            "Postal_Code": "95054",
            "Rehired_Employee": "No",
            "Org_Level_1": "All R&D",
            "Org_Level_3": "FWaaP",
            "Country_Name": "United States Of America",
            "Org_Level_2": "Enterprise R&D",
            "Emp_ID": "115104",
            "Job_Family": "Software Engineering",
            "Preferred_Name_-_First_Name": "Tooth",
            "Prehire_Flag": "False",
            "Management_Level_1": "Nikesh Arora",
            "Work_Country_Abbrev": "US",
            "Management_Level_2": "Timmy Turner",
            "Email_Address": "tfairy@test.com",
            "Title": "Staff Engineer SW",
            "City": "Santa Clara",
            "Work_State_US_Only": "California",
            "Job_Code": "5162",
            "PAN_CF_Okta_Location_Region": "Americas",
            "Last_Name": "Fairy_Updated",
            "Job_Function": "Engineering Function",
            "State": "California",
            "Exec_Admin_Flag": "N",
            "Preferred_Name": "Tooth Fairy_Updated",
            "Regular_Employee_Flag": "Y",
            "Preferred_Name_-_Last_Name": "Fairy_Updated",
            "Cost_Center_Code": "613116",
            "Location": "Office - USA - CA - Headquarters"
        },
        {
            "Employee_Type": "Regular",
            "Leadership": "No",
            "Work_Country_Code": "840",
            "Street_Address": "3000 Tannery Way",
            "Employment_Status": "Active",
            "VP_Flag": "N",
            "Mgr_ID": "115069",
            "Cost_Center_Description": "Consulting Systems Engineering",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "test26@testing.com",
            "First_Name": "Remy",
            "Last_Hire_Date": "06/15/2020",
            "People_Manager_Flag": "N",
            "Department": "WW Sales Functions:WW SE Sales",
            "Workday_ID": "9aa7e309929e01830c041f1c08039323",
            "Postal_Code": "95054",
            "Rehired_Employee": "No",
            "Org_Level_1": "Sales",
            "Org_Level_3": "WW SE Sales",
            "Country_Name": "United States Of America",
            "Org_Level_2": "WW Sales Functions",
            "Emp_ID": "115094",
            "Job_Family": "Software Engineering",
            "User_Name": "rbuxaplenty@test.com",
            "Preferred_Name_-_First_Name": "Remy",
            "Prehire_Flag": "False",
            "Management_Level_1": "Nikesh Arora",
            "Work_Country_Abbrev": "US",
            "Management_Level_2": "Timmy Turner",
            "Email_Address": "rbuxaplenty@test.com",
            "Title": "Staff Engineer Software",
            "City": "Santa Clara",
            "Work_State_US_Only": "California",
            "Job_Code": "5162",
            "PAN_CF_Okta_Location_Region": "Americas",
            "Last_Name": "Buxaplenty",
            "Job_Function": "Engineering Function",
            "State": "California",
            "Exec_Admin_Flag": "N",
            "Preferred_Name": "Remy Buxaplenty",
            "Regular_Employee_Flag": "Y",
            "Preferred_Name_-_Last_Name": "Buxaplenty",
            "Cost_Center_Code": "310100",
            "Location": "Office - USA - CA - Headquarters"
        },
        {
            "Emp_ID": "115098",
            "Leadership": "No",
            "Work_Country_Code": "0",
            "Employment_Status": "Active",
            "User_Name": "cocarmichael",
            "Preferred_Name_-_First_Name": "Connie",
            "Prehire_Flag": "False",
            "VP_Flag": "N",
            "Email_Address": "cocarmichael@test.com",
            "Title": "Systems Engineer Specialist",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "test30@testing.com",
            "First_Name": "Connie",
            "People_Manager_Flag": "N",
            "Last_Name": "Carmichael",
            "Exec_Admin_Flag": "N",
            "Workday_ID": "9aa7e309929e01a58ac35f1508030820",
            "Preferred_Name": "Connie Carmichael",
            "Rehired_Employee": "No",
            "Regular_Employee_Flag": "N",
            "Preferred_Name_-_Last_Name": "Carmichael"
        },
        {
            "Employee_Type": "Regular",
            "Leadership": "No",
            "Work_Country_Code": "840",
            "Street_Address": "3000 Tannery Way",
            "Employment_Status": "Active",
            "VP_Flag": "N",
            "Mgr_ID": "115069",
            "Cost_Center_Description": "IoT - PM",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "test24@testing.com",
            "First_Name": "Norm",
            "Last_Hire_Date": "06/15/2020",
            "People_Manager_Flag": "N",
            "Department": "Enterprise R&D:FWaaP",
            "Workday_ID": "9aa7e309929e0125823a032108030b25",
            "Postal_Code": "95054",
            "Rehired_Employee": "No",
            "Org_Level_1": "All R&D",
            "Org_Level_3": "FWaaP",
            "Country_Name": "United States Of America",
            "Org_Level_2": "Enterprise R&D",
            "Emp_ID": "115092",
            "Job_Family": "Product Management",
            "User_Name": "ngenie@test.com",
            "Preferred_Name_-_First_Name": "Norm",
            "Prehire_Flag": "False",
            "Management_Level_1": "Nikesh Arora",
            "Work_Country_Abbrev": "US",
            "Management_Level_2": "Timmy Turner",
            "Email_Address": "ngenie@test.com",
            "Title": "Sr Prod Mgr",
            "City": "Santa Clara",
            "Work_State_US_Only": "California",
            "Job_Code": "5224",
            "PAN_CF_Okta_Location_Region": "Americas",
            "Last_Name": "Genie",
            "Job_Function": "Product Management Function",
            "State": "California",
            "Exec_Admin_Flag": "N",
            "Preferred_Name": "Norm Genie",
            "Regular_Employee_Flag": "Y",
            "Preferred_Name_-_Last_Name": "Genie",
            "Cost_Center_Code": "651116",
            "Location": "Office - USA - CA - Headquarters"
        },
        {
            "Employee_Type": "Regular",
            "Leadership": "No",
            "Work_Country_Code": "840",
            "Street_Address": "3000 Tannery Way",
            "Employment_Status": "Active",
            "VP_Flag": "N",
            "Mgr_ID": "115069",
            "Cost_Center_Description": "IoT - PM",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "test23@testing.com",
            "First_Name": "Santa",
            "Last_Hire_Date": "06/15/2020",
            "People_Manager_Flag": "N",
            "Department": "Enterprise R&D:FWaaP",
            "Workday_ID": "9aa7e309929e01b392c9a5220803c825",
            "Postal_Code": "95054",
            "Rehired_Employee": "No",
            "Org_Level_1": "All R&D",
            "Org_Level_3": "FWaaP",
            "Country_Name": "United States Of America",
            "Org_Level_2": "Enterprise R&D",
            "Emp_ID": "115091",
            "Job_Family": "Technical Writing",
            "Preferred_Name_-_First_Name": "Santa",
            "Prehire_Flag": "False",
            "Management_Level_1": "Nikesh Arora",
            "Work_Country_Abbrev": "US",
            "Management_Level_2": "Timmy Turner",
            "Email_Address": "sclaus@test.com",
            "Title": "Sr Technical Writer",
            "City": "Santa Clara",
            "Work_State_US_Only": "California",
            "Job_Code": "5314",
            "PAN_CF_Okta_Location_Region": "Americas",
            "Last_Name": "Claus",
            "Job_Function": "Product Management Function",
            "State": "California",
            "Exec_Admin_Flag": "N",
            "Preferred_Name": "Santa Claus",
            "Regular_Employee_Flag": "Y",
            "Preferred_Name_-_Last_Name": "Claus",
            "Cost_Center_Code": "651116",
            "Location": "Office - USA - CA - Headquarters"
        },
        {
            "Employee_Type": "Regular",
            "Leadership": "No",
            "Work_Country_Code": "840",
            "Street_Address": "3000 Tannery Way",
            "Employment_Status": "Active",
            "VP_Flag": "N",
            "Mgr_ID": "115069",
            "Cost_Center_Description": "IoT - PM",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "test20@testing.com",
            "First_Name": "Dolores",
            "Last_Hire_Date": "06/15/2020",
            "People_Manager_Flag": "N",
            "Department": "Enterprise R&D:FWaaP",
            "Workday_ID": "9aa7e309929e0188f4eb6b2a08031228",
            "Postal_Code": "95054",
            "Rehired_Employee": "No",
            "Org_Level_1": "All R&D",
            "Org_Level_3": "FWaaP",
            "Country_Name": "United States Of America",
            "Org_Level_2": "Enterprise R&D",
            "Emp_ID": "115088",
            "Job_Family": "Software Engineering",
            "Preferred_Name_-_First_Name": "Dolores",
            "Prehire_Flag": "False",
            "Management_Level_1": "Nikesh Arora",
            "Work_Country_Abbrev": "US",
            "Management_Level_2": "Timmy Turner",
            "Email_Address": "dcrocker@test.com",
            "Title": "Sr Mgr, UX Design",
            "City": "Santa Clara",
            "Work_State_US_Only": "California",
            "Job_Code": "2164",
            "PAN_CF_Okta_Location_Region": "Americas",
            "Last_Name": "Crocker",
            "Job_Function": "Engineering Function",
            "State": "California",
            "Exec_Admin_Flag": "N",
            "Preferred_Name": "Dolores Crocker",
            "Regular_Employee_Flag": "Y",
            "Preferred_Name_-_Last_Name": "Crocker",
            "Cost_Center_Code": "651116",
            "Location": "Office - USA - CA - Headquarters"
        },
        {
            "Employee_Type": "Regular",
            "Leadership": "No",
            "Work_Country_Code": "840",
            "Street_Address": "3000 Tannery Way",
            "Employment_Status": "Active",
            "VP_Flag": "N",
            "Mgr_ID": "115069",
            "Cost_Center_Description": "IoT - Engineering",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "test19@testing.com",
            "First_Name": "Crash",
            "Last_Hire_Date": "06/15/2020",
            "People_Manager_Flag": "N",
            "Department": "Enterprise R&D:FWaaP",
            "Workday_ID": "9aa7e309929e014a0d78ca2c08030629",
            "Postal_Code": "95054",
            "Rehired_Employee": "No",
            "Org_Level_1": "All R&D",
            "Org_Level_3": "FWaaP",
            "Country_Name": "United States Of America",
            "Org_Level_2": "Enterprise R&D",
            "Emp_ID": "115087",
            "Job_Family": "Software Engineering",
            "Preferred_Name_-_First_Name": "Crash",
            "Prehire_Flag": "False",
            "Management_Level_1": "Nikesh Arora",
            "Work_Country_Abbrev": "US",
            "Management_Level_2": "Timmy Turner",
            "Email_Address": "cnebula@test.com",
            "Title": "Staff Engineer Software",
            "City": "Santa Clara",
            "Work_State_US_Only": "California",
            "Job_Code": "5162",
            "PAN_CF_Okta_Location_Region": "Americas",
            "Last_Name": "Nebula",
            "Job_Function": "Engineering Function",
            "State": "California",
            "Exec_Admin_Flag": "N",
            "Preferred_Name": "Crash Nebula",
            "Regular_Employee_Flag": "Y",
            "Preferred_Name_-_Last_Name": "Nebula",
            "Cost_Center_Code": "613116",
            "Location": "Office - USA - CA - Headquarters"
        },
        {
            "Employee_Type": "Regular",
            "Leadership": "No",
            "Work_Country_Code": "840",
            "Street_Address": "3000 Tannery Way",
            "Employment_Status": "Active",
            "VP_Flag": "N",
            "Mgr_ID": "115069",
            "Cost_Center_Description": "IoT - Engineering",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "test18@testing.com",
            "First_Name": "Trixie",
            "Last_Hire_Date": "06/15/2020",
            "People_Manager_Flag": "N",
            "Department": "Enterprise R&D:FWaaP",
            "Workday_ID": "9aa7e309929e01eb443ce92e08031f2a",
            "Postal_Code": "95054",
            "Rehired_Employee": "No",
            "Org_Level_1": "All R&D",
            "Org_Level_3": "FWaaP",
            "Country_Name": "United States Of America",
            "Org_Level_2": "Enterprise R&D",
            "Emp_ID": "115086",
            "Job_Family": "Software Engineering",
            "Preferred_Name_-_First_Name": "Trixie",
            "Prehire_Flag": "False",
            "Management_Level_1": "Nikesh Arora",
            "Work_Country_Abbrev": "US",
            "Management_Level_2": "Timmy Turner",
            "Email_Address": "ttang@test.com",
            "Title": "Principal Engineer Software",
            "City": "Santa Clara",
            "Work_State_US_Only": "California",
            "Job_Code": "5164",
            "PAN_CF_Okta_Location_Region": "Americas",
            "Last_Name": "Tang",
            "Job_Function": "Engineering Function",
            "State": "California",
            "Exec_Admin_Flag": "N",
            "Preferred_Name": "Trixie Tang",
            "Regular_Employee_Flag": "Y",
            "Preferred_Name_-_Last_Name": "Tang",
            "Cost_Center_Code": "613116",
            "Location": "Office - USA - CA - Headquarters"
        }
    ]
}

NEW_HIRE_REPORT = {
    "Report_Entry": [
        {
            "Employee_Type": "Regular",
            "Leadership": "No",
            "Work_Country_Code": "840",
            "Street_Address": "3000 Tannery Way",
            "Employment_Status": "Active",
            "VP_Flag": "N",
            "Mgr_ID": "115069",
            "Cost_Center_Description": "IoT - PM",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "test6@testing.com",
            "First_Name": "Chester",
            "Last_Hire_Date": "06/15/2020",
            "People_Manager_Flag": "N",
            "Department": "Enterprise R&D:FWaaP",
            "Workday_ID": "9aa7e309929e013ff3c6e3440803b833",
            "Postal_Code": "95054",
            "Rehired_Employee": "No",
            "Org_Level_1": "All R&D",
            "Org_Level_3": "FWaaP",
            "Country_Name": "United States Of America",
            "Org_Level_2": "Enterprise R&D",
            "Emp_ID": "115074",
            "Job_Family": "Product Management",
            "Preferred_Name_-_First_Name": "Chester",
            "Nikesh Arora": "False",
            "Management_Level_1": "Nikesh Arora",
            "Work_Country_Abbrev": "US",
            "Management_Level_2": "Timmy Turner",
            "Email_Address": "cmcbadbat@test.com",
            "Title": "Product Line Manager",
            "City": "Santa Clara",
            "Work_State_US_Only": "California",
            "Job_Code": "5225",
            "PAN_CF_Okta_Location_Region": "Americas",
            "Last_Name": "McBadbat",
            "Job_Function": "Product Management Function",
            "State": "California",
            "Exec_Admin_Flag": "N",
            "Preferred_Name": "Chester McBadbat",
            "Regular_Employee_Flag": "Y",
            "Preferred_Name_-_Last_Name": "McBadbat",
            "Cost_Center_Code": "651116",
            "Location": "Office - USA - CA - Headquarters"
        },
        {
            "Employee_Type": "Regular",
            "Leadership": "No",
            "Work_Country_Code": "840",
            "Street_Address": "3000 Tannery Way",
            "Employment_Status": "Active",
            "VP_Flag": "N",
            "Mgr_ID": "115069",
            "Cost_Center_Description": "IoT - Engineering",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "test5@testing.com",
            "First_Name": "Crimson",
            "Last_Hire_Date": "06/15/2020",
            "People_Manager_Flag": "N",
            "Department": "Enterprise R&D:FWaaP",
            "Workday_ID": "9aa7e309929e0184fd07b3460803cd34",
            "Postal_Code": "95054",
            "Rehired_Employee": "No",
            "Org_Level_1": "All R&D",
            "Org_Level_3": "FWaaP",
            "Country_Name": "United States Of America",
            "Org_Level_2": "Enterprise R&D",
            "Emp_ID": "115073",
            "Job_Family": "Software Engineering",
            "Preferred_Name_-_First_Name": "Crimson",
            "Nikesh Arora": "False",
            "Management_Level_1": "Nikesh Arora",
            "Work_Country_Abbrev": "US",
            "Management_Level_2": "Timmy Turner",
            "Email_Address": "cchin@test.com",
            "Title": "Principal Engineer Software",
            "City": "Santa Clara",
            "Work_State_US_Only": "California",
            "Job_Code": "5164",
            "PAN_CF_Okta_Location_Region": "Americas",
            "Last_Name": "Chin",
            "Job_Function": "Engineering Function",
            "State": "California",
            "Exec_Admin_Flag": "N",
            "Preferred_Name": "Crimson Chin",
            "Regular_Employee_Flag": "Y",
            "Preferred_Name_-_Last_Name": "Chin",
            "Cost_Center_Code": "613116",
            "Location": "Office - USA - CA - Headquarters"
        },
        {
            "Employee_Type": "Regular",
            "Leadership": "No",
            "Work_Country_Code": "840",
            "Street_Address": "3000 Tannery Way",
            "Employment_Status": "Active",
            "VP_Flag": "N",
            "Mgr_ID": "115069",
            "Cost_Center_Description": "IoT - Engineering",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "test4@testing.com",
            "First_Name": "Chloe",
            "Last_Hire_Date": "06/15/2020",
            "People_Manager_Flag": "N",
            "Department": "Enterprise R&D:FWaaP",
            "Workday_ID": "9aa7e309929e01fb90f1a3480803bd35",
            "Postal_Code": "95054",
            "Rehired_Employee": "No",
            "Org_Level_1": "All R&D",
            "Org_Level_3": "FWaaP",
            "Country_Name": "United States Of America",
            "Org_Level_2": "Enterprise R&D",
            "Emp_ID": "115072",
            "Job_Family": "Software Engineering",
            "Preferred_Name_-_First_Name": "Chloe",
            "Nikesh Arora": "False",
            "Management_Level_1": "Nikesh Arora",
            "Work_Country_Abbrev": "US",
            "Management_Level_2": "Timmy Turner",
            "Email_Address": "ccarmichael@test.com",
            "Title": "Sr Mgr, SW Engineering",
            "City": "Santa Clara",
            "Work_State_US_Only": "California",
            "Job_Code": "2164",
            "PAN_CF_Okta_Location_Region": "Americas",
            "Last_Name": "Carmichael",
            "Job_Function": "Engineering Function",
            "State": "California",
            "Exec_Admin_Flag": "N",
            "Preferred_Name": "Chloe Carmichael",
            "Regular_Employee_Flag": "Y",
            "Preferred_Name_-_Last_Name": "Carmichael",
            "Cost_Center_Code": "613116",
            "Location": "Office - USA - CA - Headquarters"
        }
    ]
}

UPDATE_REPORT = {
    "Report_Entry": [
        {
            "Employee_Type": "Regular",
            "Leadership": "Yes-HQ",
            "Work_Country_Code": "840",
            "Street_Address": "Updated_3000 Tannery Way",
            "Employment_Status": "Active",
            "VP_Flag": "N",
            "Mgr_ID": "115069",
            "Cost_Center_Description": "Channel Sales",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "Y",
            "Email_-_Primary_Home": "ronnyrahardjo@test.com",
            "First_Name": "Ronny",
            "Last_Hire_Date": "10/05/2020",
            "People_Manager_Flag": "N",
            "Department": "Sales NAM:NAM Channel Sales",
            "Workday_ID": "5aa443c785ff10461ac83e5a6be32e1e",
            "Postal_Code": "95054",
            "Rehired_Employee": "Yes",
            "Org_Level_1": "Sales",
            "Org_Level_3": "NAM Channel Sales",
            "Country_Name": "United States Of America",
            "Org_Level_2": "Sales NAM",
            "Emp_ID": "100122",
            "Job_Family": "Product Management",
            "User_Name": "rrahardjo@test.com",
            "Preferred_Name_-_First_Name": "Ronny",
            "Prehire_Flag": "False",
            "Management_Level_1": "Nikesh Arora_Updated",
            "Work_Country_Abbrev": "US",
            "Management_Level_2": "Timmy Turner",
            "Email_Address": "rrahardjo@test.com",
            "Title": "Dir, Product Line Manager",
            "City": "Santa Clara",
            "Work_State_US_Only": "California",
            "Job_Code": "2245",
            "PAN_CF_Okta_Location_Region": "Americas",
            "Last_Name": "Rahardjo",
            "Job_Function": "Product Management Function",
            "State": "California",
            "Exec_Admin_Flag": "N",
            "Preferred_Name": "Ronny Rahardjo",
            "Regular_Employee_Flag": "Y",
            "Preferred_Name_-_Last_Name": "Rahardjo",
            "Cost_Center_Code": "120100",
            "Location": "Office - USA - CA - Headquarters"
        },
        {
            "Employee_Type": "Regular",
            "Leadership": "No",
            "Work_Country_Code": "840",
            "Street_Address": "Updated_WeWork Embarcadero Center",
            "Employment_Status": "Active",
            "VP_Flag": "N",
            "Mgr_ID": "115069",
            "Cost_Center_Description": "Magnifier Sales Inc",
            "GDPR_Country_Flag": "0",
            "Public_Work_Mobile_Phone_Number": "+44  7900-160-819",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "stevearnoldtstc@test.com",
            "First_Name": "Stephen",
            "Last_Hire_Date": "10/01/2020",
            "People_Manager_Flag": "N",
            "Department": "WW Sales Functions:Cortex Sales",
            "Workday_ID": "5aa443c785ff10461a941c31a173e459",
            "Postal_Code": "94111",
            "Rehired_Employee": "Yes",
            "Org_Level_1": "Sales",
            "Org_Level_3": "Cortex Sales",
            "Country_Name": "United States Of America",
            "Org_Level_2": "WW Sales Functions",
            "Emp_ID": "101351",
            "Job_Family": "Software Engineering",
            "User_Name": "sarnold@test.com",
            "Preferred_Name_-_First_Name": "Stephen",
            "Prehire_Flag": "False",
            "Management_Level_1": "Nikesh Arora_Updated",
            "Work_Country_Abbrev": "US",
            "Management_Level_2": "Timmy Turner",
            "Email_Address": "sarnold@test.com",
            "Title": "Mgr, SW Engineering",
            "City": "San Francisco",
            "Work_State_US_Only": "California",
            "Job_Code": "2163",
            "PAN_CF_Okta_Location_Region": "Americas",
            "Last_Name": "Arnold",
            "Job_Function": "Engineering Function",
            "State": "California",
            "Exec_Admin_Flag": "N",
            "Preferred_Name": "Stephen Arnold",
            "Regular_Employee_Flag": "Y",
            "Preferred_Name_-_Last_Name": "Arnold",
            "Cost_Center_Code": "101100",
            "Location": "Office - USA - CA - San Francisco"
        },
        {
            "Emp_ID": "115098",
            "Leadership": "No",
            "Work_Country_Code": "0",
            "Employment_Status": "Active",
            "User_Name": "cocarmichael",
            "Preferred_Name_-_First_Name": "Connie",
            "Prehire_Flag": "False",
            "VP_Flag": "N",
            "Email_Address": "cocarmichael@test.com",
            "Title": "Systems Engineer Specialist",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "test30@testing.com",
            "First_Name": "Connie",
            "People_Manager_Flag": "N",
            "Last_Name": "Carmichael",
            "Exec_Admin_Flag": "N",
            "Workday_ID": "9aa7e309929e01a58ac35f1508030820",
            "Preferred_Name": "Connie Carmichael",
            "Rehired_Employee": "No",
            "Regular_Employee_Flag": "N",
            "Preferred_Name_-_Last_Name": "Carmichael",
            "Last_Hire_Date": "01/22/2018",
            "Termination_Date": "01/23/2047"
        }
    ]
}

TERMINATE_USER_REPORT = {
    "Report_Entry": [
        {
            "Employee_Type": "Regular",
            "Leadership": "No",
            "Work_Country_Code": "840",
            "Street_Address": "Updated_3000 Tannery Way",
            "Employment_Status": "Terminated",
            "VP_Flag": "N",
            "Mgr_ID": "115069",
            "Cost_Center_Description": "IoT - PM",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "test6@testing.com",
            "First_Name": "Chester",
            "Last_Hire_Date": "06/15/2020",
            "People_Manager_Flag": "N",
            "Department": "Enterprise R&D:FWaaP",
            "Workday_ID": "9aa7e309929e013ff3c6e3440803b833",
            "Postal_Code": "95054",
            "Rehired_Employee": "No",
            "Org_Level_1": "All R&D",
            "Org_Level_3": "FWaaP",
            "Country_Name": "United States Of America",
            "Org_Level_2": "Enterprise R&D",
            "Emp_ID": "115074",
            "Job_Family": "Product Management",
            "Preferred_Name_-_First_Name": "Chester",
            "Prehire_Flag": "False",
            "Management_Level_1": "Nikesh Arora_Updated",
            "Work_Country_Abbrev": "US",
            "Management_Level_2": "Timmy Turner",
            "Email_Address": "cmcbadbat@test.com",
            "Title": "Product Line Manager",
            "City": "Santa Clara",
            "Work_State_US_Only": "California",
            "Job_Code": "5225",
            "PAN_CF_Okta_Location_Region": "Americas",
            "Last_Name": "McBadbat",
            "Job_Function": "Product Management Function",
            "State": "California",
            "Exec_Admin_Flag": "N",
            "Preferred_Name": "Chester McBadbat",
            "Regular_Employee_Flag": "Y",
            "Preferred_Name_-_Last_Name": "McBadbat",
            "Cost_Center_Code": "651116",
            "Location": "Office - USA - CA - Headquarters"
        },
        {
            "Employee_Type": "Regular",
            "Leadership": "Yes-HQ",
            "Work_Country_Code": "840",
            "Street_Address": "Updated_3000 Tannery Way",
            "Employment_Status": "Terminated",
            "VP_Flag": "Y",
            "Mgr_ID": "115069",
            "Cost_Center_Description": "IoT - PM",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "test3@testing.com",
            "First_Name": "Icky",
            "Last_Hire_Date": "06/15/2020",
            "People_Manager_Flag": "N",
            "Department": "Enterprise R&D:FWaaP",
            "Workday_ID": "9aa7e309929e01abc779c14a0803b936",
            "Postal_Code": "95054",
            "Rehired_Employee": "No",
            "Org_Level_1": "All R&D",
            "Org_Level_3": "FWaaP",
            "Country_Name": "United States Of America",
            "Org_Level_2": "Enterprise R&D",
            "Emp_ID": "115071",
            "Job_Family": "Engineering - Executive",
            "Preferred_Name_-_First_Name": "Icky",
            "Prehire_Flag": "False",
            "Management_Level_1": "Nikesh Arora_Updated",
            "Work_Country_Abbrev": "US",
            "Management_Level_2": "Timmy Turner",
            "Email_Address": "ivicky@test.com",
            "Title": "VP, Products",
            "City": "Santa Clara",
            "Work_State_US_Only": "California",
            "Job_Code": "2007",
            "PAN_CF_Okta_Location_Region": "Americas",
            "Last_Name": "Vicky",
            "Job_Function": "Engineering Function",
            "State": "California",
            "Exec_Admin_Flag": "N",
            "Preferred_Name": "Icky Vicky",
            "Regular_Employee_Flag": "Y",
            "Preferred_Name_-_Last_Name": "Vicky",
            "Cost_Center_Code": "651116",
            "Location": "Office - USA - CA - Headquarters"
        },
        {
            "Emp_ID": "115100",
            "Leadership": "No",
            "Work_Country_Code": "0",
            "Employment_Status": "Active",
            "User_Name": "bhartman",
            "Preferred_Name_-_First_Name": "Butch",
            "Prehire_Flag": "False",
            "VP_Flag": "N",
            "Email_Address": "bhartman@test.com",
            "Title": "Sr Staff Engineer Software",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "test33@testing.com",
            "First_Name": "Butch",
            "People_Manager_Flag": "N",
            "Last_Name": "Hartman",
            "Exec_Admin_Flag": "N",
            "Workday_ID": "9aa7e309929e01e7d82293110803571e",
            "Preferred_Name": "Butch Hartman",
            "Rehired_Employee": "No",
            "Regular_Employee_Flag": "N",
            "Preferred_Name_-_Last_Name": "Hartman",
            "Last_Hire_Date": "04/17/2019",
            "Termination_Date": "01/03/2020"
        }
    ]
}

REHIRE_USER_REPORT = {
    "Report_Entry": [
        {
            "Employee_Type": "Regular",
            "Leadership": "No",
            "Work_Country_Code": "840",
            "Street_Address": "Updated_3000 Tannery Way",
            "Employment_Status": "Terminated",
            "VP_Flag": "N",
            "Mgr_ID": "115069",
            "Cost_Center_Description": "IoT - PM",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "test6@testing.com",
            "First_Name": "Chester",
            "Last_Hire_Date": "06/15/2020",
            "People_Manager_Flag": "N",
            "Department": "Enterprise R&D:FWaaP",
            "Workday_ID": "9aa7e309929e013ff3c6e3440803b833",
            "Postal_Code": "95054",
            "Rehired_Employee": "Yes",
            "Org_Level_1": "All R&D",
            "Org_Level_3": "FWaaP",
            "Country_Name": "United States Of America",
            "Org_Level_2": "Enterprise R&D",
            "Emp_ID": "115074",
            "Job_Family": "Product Management",
            "Preferred_Name_-_First_Name": "Chester",
            "Prehire_Flag": "True",
            "Management_Level_1": "Nikesh Arora_Updated",
            "Work_Country_Abbrev": "US",
            "Management_Level_2": "Timmy Turner",
            "Email_Address": "cmcbadbat@test.com",
            "Title": "Product Line Manager",
            "City": "Santa Clara",
            "Work_State_US_Only": "California",
            "Job_Code": "5225",
            "PAN_CF_Okta_Location_Region": "Americas",
            "Last_Name": "McBadbat",
            "Job_Function": "Product Management Function",
            "State": "California",
            "Exec_Admin_Flag": "N",
            "Preferred_Name": "Chester McBadbat",
            "Regular_Employee_Flag": "Y",
            "Preferred_Name_-_Last_Name": "McBadbat",
            "Cost_Center_Code": "651116",
            "Location": "Office - USA - CA - Headquarters"
        },
        {
            "Employee_Type": "Regular",
            "Leadership": "Yes-HQ",
            "Work_Country_Code": "840",
            "Street_Address": "Updated_3000 Tannery Way",
            "Employment_Status": "Terminated",
            "VP_Flag": "Y",
            "Mgr_ID": "115069",
            "Cost_Center_Description": "IoT - PM",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "test3@testing.com",
            "First_Name": "Icky",
            "Last_Hire_Date": "06/15/2020",
            "People_Manager_Flag": "N",
            "Department": "Enterprise R&D:FWaaP",
            "Workday_ID": "9aa7e309929e01abc779c14a0803b936",
            "Postal_Code": "95054",
            "Rehired_Employee": "Yes",
            "Org_Level_1": "All R&D",
            "Org_Level_3": "FWaaP",
            "Country_Name": "United States Of America",
            "Org_Level_2": "Enterprise R&D",
            "Emp_ID": "115071",
            "Job_Family": "Engineering - Executive",
            "Preferred_Name_-_First_Name": "Icky",
            "Prehire_Flag": "True",
            "Management_Level_1": "Nikesh Arora_Updated",
            "Work_Country_Abbrev": "US",
            "Management_Level_2": "Timmy Turner",
            "Email_Address": "ivicky@test.com",
            "Title": "VP, Products",
            "City": "Santa Clara",
            "Work_State_US_Only": "California",
            "Job_Code": "2007",
            "PAN_CF_Okta_Location_Region": "Americas",
            "Last_Name": "Vicky",
            "Job_Function": "Engineering Function",
            "State": "California",
            "Exec_Admin_Flag": "N",
            "Preferred_Name": "Icky Vicky",
            "Regular_Employee_Flag": "Y",
            "Preferred_Name_-_Last_Name": "Vicky",
            "Cost_Center_Code": "651116",
            "Location": "Office - USA - CA - Headquarters"
        },
        {
            "Emp_ID": "115100",
            "Leadership": "No",
            "Work_Country_Code": "0",
            "Employment_Status": "Active",
            "User_Name": "bhartman",
            "Preferred_Name_-_First_Name": "Butch",
            "Prehire_Flag": "True",
            "VP_Flag": "N",
            "Email_Address": "bhartman@test.com",
            "Title": "Sr Staff Engineer Software",
            "GDPR_Country_Flag": "0",
            "Director_Flag": "N",
            "Email_-_Primary_Home": "test33@testing.com",
            "First_Name": "Butch",
            "People_Manager_Flag": "N",
            "Last_Name": "Hartman",
            "Exec_Admin_Flag": "N",
            "Workday_ID": "9aa7e309929e01e7d82293110803571e",
            "Preferred_Name": "Butch Hartman",
            "Rehired_Employee": "Yes",
            "Regular_Employee_Flag": "N",
            "Preferred_Name_-_Last_Name": "Hartman",
            "Last_Hire_Date": "04/17/2020",
            "Termination_Date": "01/03/2025"
        }
    ]
}

APP: Flask = Flask('xsoar-workday')


@APP.route('/', methods=['GET'])
def generate_event():
    event_type = demisto.args().get('event_type')
    user_email = demisto.args().get('user_email')
    if event_type == 'hire':
        get_new_hire_reports(user_email)
    elif event_type == 'update':
        get_update_report(user_email)
    elif event_type == 'rehire':
        get_rehire_report(user_email)
    elif event_type == 'terminate':
        get_terminate_report(user_email)

    integration_context = get_integration_context()
    return jsonify(integration_context)


def get_new_hire_reports(user_email):
    if not user_email:
        set_integration_context(NEW_HIRE_REPORT)
    else:
        integration_context = get_integration_context()
        reports = NEW_HIRE_REPORT['Report_Entry']
        for report in reports:
            email = report.get('Email_Address')
            if email == user_email:
                integration_context['Report_Entry'].append(report)
                set_integration_context(integration_context)


def get_terminate_report(user_email):
    if not user_email:
        set_integration_context(TERMINATE_USER_REPORT)
    else:
        integration_context = get_integration_context()
        reports = TERMINATE_USER_REPORT['Report_Entry']
        for report in reports:
            email = report.get('Email_Address')
            if email == user_email:
                users = [i for i in integration_context['Report_Entry'] if not (i['Email_Address'] == email)]
                users.append(report)
                integration_context['Report_Entry'] = users
                set_integration_context(integration_context)


def get_update_report(user_email):
    if not user_email:
        set_integration_context(UPDATE_REPORT)
    else:
        integration_context = get_integration_context()
        reports = UPDATE_REPORT['Report_Entry']
        for report in reports:
            email = report.get('Email_Address')
            if email == user_email:
                users = [i for i in integration_context['Report_Entry'] if not (i['Email_Address'] == email)]
                users.append(report)
                integration_context['Report_Entry'] = users
                set_integration_context(integration_context)


def get_rehire_report(user_email):
    if not user_email:
        set_integration_context(REHIRE_USER_REPORT)
    else:
        integration_context = get_integration_context()
        reports = REHIRE_USER_REPORT['Report_Entry']
        for report in reports:
            email = report.get('Email_Address')
            if email == user_email:
                users = [i for i in integration_context['Report_Entry'] if not (i['Email_Address'] == email)]
                users.append(report)
                integration_context['Report_Entry'] = users
                set_integration_context(integration_context)


if demisto.command() == 'long-running-execution':
    integration_context = get_integration_context()
    if not integration_context:
        set_integration_context(FIRST_RUN_REPORT)
    while True:
        port = int(demisto.params().get('longRunningPort', ''))
        server = WSGIServer(('0.0.0.0', port), APP)
        server.serve_forever()


elif demisto.command() == 'generate-event':
    generate_event()

elif demisto.command() == 'initialize-context':
    set_integration_context(FIRST_RUN_REPORT)
    return_results('The integration context has been initialized.')
