import demistomock as demisto
from CommonServerPython import *
from CommonServerUserPython import *


# ISO 3166-1-derived mapping (begin)
COUNTRIES = dict(
    AW=dict(name="Aruba"),
    AF=dict(name="Afghanistan"),
    AO=dict(name="Angola"),
    AI=dict(name="Anguilla"),
    AX=dict(name="Åland Islands"),
    AL=dict(name="Albania"),
    AD=dict(name="Andorra"),
    AE=dict(name="United Arab Emirates"),
    AR=dict(name="Argentina"),
    AM=dict(name="Armenia"),
    AS=dict(name="American Samoa"),
    AQ=dict(name="Antarctica"),
    TF=dict(name="French Southern Territories"),
    AG=dict(name="Antigua and Barbuda"),
    AU=dict(name="Australia"),
    AT=dict(name="Austria"),
    AZ=dict(name="Azerbaijan"),
    BI=dict(name="Burundi"),
    BE=dict(name="Belgium"),
    BJ=dict(name="Benin"),
    BQ=dict(name="Bonaire, Sint Eustatius and Saba"),
    BF=dict(name="Burkina Faso"),
    BD=dict(name="Bangladesh"),
    BG=dict(name="Bulgaria"),
    BH=dict(name="Bahrain"),
    BS=dict(name="Bahamas"),
    BA=dict(name="Bosnia and Herzegovina"),
    BL=dict(name="Saint Barthélemy"),
    BY=dict(name="Belarus"),
    BZ=dict(name="Belize"),
    BM=dict(name="Bermuda"),
    BO=dict(name="Bolivia, Plurinational State of"),
    BR=dict(name="Brazil"),
    BB=dict(name="Barbados"),
    BN=dict(name="Brunei Darussalam"),
    BT=dict(name="Bhutan"),
    BV=dict(name="Bouvet Island"),
    BW=dict(name="Botswana"),
    CF=dict(name="Central African Republic"),
    CA=dict(name="Canada"),
    CC=dict(name="Cocos (Keeling) Islands"),
    CH=dict(name="Switzerland"),
    CL=dict(name="Chile"),
    CN=dict(name="China"),
    CI=dict(name="Côte d'Ivoire"),
    CM=dict(name="Cameroon"),
    CD=dict(name="Congo, The Democratic Republic of the"),
    CG=dict(name="Congo"),
    CK=dict(name="Cook Islands"),
    CO=dict(name="Colombia"),
    KM=dict(name="Comoros"),
    CV=dict(name="Cabo Verde"),
    CR=dict(name="Costa Rica"),
    CU=dict(name="Cuba"),
    CW=dict(name="Curaçao"),
    CX=dict(name="Christmas Island"),
    KY=dict(name="Cayman Islands"),
    CY=dict(name="Cyprus"),
    CZ=dict(name="Czechia"),
    DE=dict(name="Germany"),
    DJ=dict(name="Djibouti"),
    DM=dict(name="Dominica"),
    DK=dict(name="Denmark"),
    DO=dict(name="Dominican Republic"),
    DZ=dict(name="Algeria"),
    EC=dict(name="Ecuador"),
    EG=dict(name="Egypt"),
    ER=dict(name="Eritrea"),
    EH=dict(name="Western Sahara"),
    ES=dict(name="Spain"),
    EE=dict(name="Estonia"),
    ET=dict(name="Ethiopia"),
    FI=dict(name="Finland"),
    FJ=dict(name="Fiji"),
    FK=dict(name="Falkland Islands (Malvinas)"),
    FR=dict(name="France"),
    FO=dict(name="Faroe Islands"),
    FM=dict(name="Micronesia, Federated States of"),
    GA=dict(name="Gabon"),
    GB=dict(name="United Kingdom"),
    GE=dict(name="Georgia"),
    GG=dict(name="Guernsey"),
    GH=dict(name="Ghana"),
    GI=dict(name="Gibraltar"),
    GN=dict(name="Guinea"),
    GP=dict(name="Guadeloupe"),
    GM=dict(name="Gambia"),
    GW=dict(name="Guinea-Bissau"),
    GQ=dict(name="Equatorial Guinea"),
    GR=dict(name="Greece"),
    GD=dict(name="Grenada"),
    GL=dict(name="Greenland"),
    GT=dict(name="Guatemala"),
    GF=dict(name="French Guiana"),
    GU=dict(name="Guam"),
    GY=dict(name="Guyana"),
    HK=dict(name="Hong Kong"),
    HM=dict(name="Heard Island and McDonald Islands"),
    HN=dict(name="Honduras"),
    HR=dict(name="Croatia"),
    HT=dict(name="Haiti"),
    HU=dict(name="Hungary"),
    ID=dict(name="Indonesia"),
    IM=dict(name="Isle of Man"),
    IN=dict(name="India"),
    IO=dict(name="British Indian Ocean Territory"),
    IE=dict(name="Ireland"),
    IR=dict(name="Iran, Islamic Republic of"),
    IQ=dict(name="Iraq"),
    IS=dict(name="Iceland"),
    IL=dict(name="Israel"),
    IT=dict(name="Italy"),
    JM=dict(name="Jamaica"),
    JE=dict(name="Jersey"),
    JO=dict(name="Jordan"),
    JP=dict(name="Japan"),
    KZ=dict(name="Kazakhstan"),
    KE=dict(name="Kenya"),
    KG=dict(name="Kyrgyzstan"),
    KH=dict(name="Cambodia"),
    KI=dict(name="Kiribati"),
    KN=dict(name="Saint Kitts and Nevis"),
    KR=dict(name="Korea, Republic of"),
    KW=dict(name="Kuwait"),
    LA=dict(name="Lao People's Democratic Republic"),
    LB=dict(name="Lebanon"),
    LR=dict(name="Liberia"),
    LY=dict(name="Libya"),
    LC=dict(name="Saint Lucia"),
    LI=dict(name="Liechtenstein"),
    LK=dict(name="Sri Lanka"),
    LS=dict(name="Lesotho"),
    LT=dict(name="Lithuania"),
    LU=dict(name="Luxembourg"),
    LV=dict(name="Latvia"),
    MO=dict(name="Macao"),
    MF=dict(name="Saint Martin (French part)"),
    MA=dict(name="Morocco"),
    MC=dict(name="Monaco"),
    MD=dict(name="Moldova, Republic of"),
    MG=dict(name="Madagascar"),
    MV=dict(name="Maldives"),
    MX=dict(name="Mexico"),
    MH=dict(name="Marshall Islands"),
    MK=dict(name="North Macedonia"),
    ML=dict(name="Mali"),
    MT=dict(name="Malta"),
    MM=dict(name="Myanmar"),
    ME=dict(name="Montenegro"),
    MN=dict(name="Mongolia"),
    MP=dict(name="Northern Mariana Islands"),
    MZ=dict(name="Mozambique"),
    MR=dict(name="Mauritania"),
    MS=dict(name="Montserrat"),
    MQ=dict(name="Martinique"),
    MU=dict(name="Mauritius"),
    MW=dict(name="Malawi"),
    MY=dict(name="Malaysia"),
    YT=dict(name="Mayotte"),
    NA=dict(name="Namibia"),
    NC=dict(name="New Caledonia"),
    NE=dict(name="Niger"),
    NF=dict(name="Norfolk Island"),
    NG=dict(name="Nigeria"),
    NI=dict(name="Nicaragua"),
    NU=dict(name="Niue"),
    NL=dict(name="Netherlands"),
    NO=dict(name="Norway"),
    NP=dict(name="Nepal"),
    NR=dict(name="Nauru"),
    NZ=dict(name="New Zealand"),
    OM=dict(name="Oman"),
    PK=dict(name="Pakistan"),
    PA=dict(name="Panama"),
    PN=dict(name="Pitcairn"),
    PE=dict(name="Peru"),
    PH=dict(name="Philippines"),
    PW=dict(name="Palau"),
    PG=dict(name="Papua New Guinea"),
    PL=dict(name="Poland"),
    PR=dict(name="Puerto Rico"),
    KP=dict(name="Korea, Democratic People's Republic of"),
    PT=dict(name="Portugal"),
    PY=dict(name="Paraguay"),
    PS=dict(name="Palestine, State of"),
    PF=dict(name="French Polynesia"),
    QA=dict(name="Qatar"),
    RE=dict(name="Réunion"),
    RO=dict(name="Romania"),
    RU=dict(name="Russian Federation"),
    RW=dict(name="Rwanda"),
    SA=dict(name="Saudi Arabia"),
    SD=dict(name="Sudan"),
    SN=dict(name="Senegal"),
    SG=dict(name="Singapore"),
    GS=dict(name="South Georgia and the South Sandwich Islands"),
    SH=dict(name="Saint Helena, Ascension and Tristan da Cunha"),
    SJ=dict(name="Svalbard and Jan Mayen"),
    SB=dict(name="Solomon Islands"),
    SL=dict(name="Sierra Leone"),
    SV=dict(name="El Salvador"),
    SM=dict(name="San Marino"),
    SO=dict(name="Somalia"),
    PM=dict(name="Saint Pierre and Miquelon"),
    RS=dict(name="Serbia"),
    SS=dict(name="South Sudan"),
    ST=dict(name="Sao Tome and Principe"),
    SR=dict(name="Suriname"),
    SK=dict(name="Slovakia"),
    SI=dict(name="Slovenia"),
    SE=dict(name="Sweden"),
    SZ=dict(name="Eswatini"),
    SX=dict(name="Sint Maarten (Dutch part)"),
    SC=dict(name="Seychelles"),
    SY=dict(name="Syrian Arab Republic"),
    TC=dict(name="Turks and Caicos Islands"),
    TD=dict(name="Chad"),
    TG=dict(name="Togo"),
    TH=dict(name="Thailand"),
    TJ=dict(name="Tajikistan"),
    TK=dict(name="Tokelau"),
    TM=dict(name="Turkmenistan"),
    TL=dict(name="Timor-Leste"),
    TO=dict(name="Tonga"),
    TT=dict(name="Trinidad and Tobago"),
    TN=dict(name="Tunisia"),
    TR=dict(name="Turkey"),
    TV=dict(name="Tuvalu"),
    TW=dict(name="Taiwan, Province of China"),
    TZ=dict(name="Tanzania, United Republic of"),
    UG=dict(name="Uganda"),
    UA=dict(name="Ukraine"),
    UM=dict(name="United States Minor Outlying Islands"),
    UY=dict(name="Uruguay"),
    US=dict(name="United States"),
    UZ=dict(name="Uzbekistan"),
    VA=dict(name="Holy See (Vatican City State)"),
    VC=dict(name="Saint Vincent and the Grenadines"),
    VE=dict(name="Venezuela, Bolivarian Republic of"),
    VG=dict(name="Virgin Islands, British"),
    VI=dict(name="Virgin Islands, U.S."),
    VN=dict(name="Viet Nam"),
    VU=dict(name="Vanuatu"),
    WF=dict(name="Wallis and Futuna"),
    WS=dict(name="Samoa"),
    YE=dict(name="Yemen"),
    ZA=dict(name="South Africa"),
    ZM=dict(name="Zambia"),
    ZW=dict(name="Zimbabwe"),
)
# ISO 3166-1-derived mapping (end)


def lookup(args):
    value = args.get("value")
    if not isinstance(value, str) or not value:
        raise ValueError("please provide a text value")

    data = COUNTRIES.get(value.upper())
    if not data:
        return value

    return data.get("name")


def main(args):
    try:
        return_results(lookup(args))
    except Exception as e:
        return_error(f"Failed to execute CyrenCountryLookup. Error: {str(e)}")


if __name__ in ("__main__", "__builtin__", "builtins"):
    main(demisto.args())
