import demistomock as demisto
from CommonServerPython import *
from CommonServerUserPython import *


# ISO 3166-1-derived mapping (begin)
COUNTRIES = dict(
    AW=dict(name="Aruba", official=""),
    AF=dict(name="Afghanistan", official="Islamic Republic of Afghanistan"),
    AO=dict(name="Angola", official="Republic of Angola"),
    AI=dict(name="Anguilla", official=""),
    AX=dict(name="Åland Islands", official=""),
    AL=dict(name="Albania", official="Republic of Albania"),
    AD=dict(name="Andorra", official="Principality of Andorra"),
    AE=dict(name="United Arab Emirates", official=""),
    AR=dict(name="Argentina", official="Argentine Republic"),
    AM=dict(name="Armenia", official="Republic of Armenia"),
    AS=dict(name="American Samoa", official=""),
    AQ=dict(name="Antarctica", official=""),
    TF=dict(name="French Southern Territories", official=""),
    AG=dict(name="Antigua and Barbuda", official=""),
    AU=dict(name="Australia", official=""),
    AT=dict(name="Austria", official="Republic of Austria"),
    AZ=dict(name="Azerbaijan", official="Republic of Azerbaijan"),
    BI=dict(name="Burundi", official="Republic of Burundi"),
    BE=dict(name="Belgium", official="Kingdom of Belgium"),
    BJ=dict(name="Benin", official="Republic of Benin"),
    BQ=dict(name="Bonaire, Sint Eustatius and Saba", official="Bonaire, Sint Eustatius and Saba"),
    BF=dict(name="Burkina Faso", official=""),
    BD=dict(name="Bangladesh", official="People's Republic of Bangladesh"),
    BG=dict(name="Bulgaria", official="Republic of Bulgaria"),
    BH=dict(name="Bahrain", official="Kingdom of Bahrain"),
    BS=dict(name="Bahamas", official="Commonwealth of the Bahamas"),
    BA=dict(name="Bosnia and Herzegovina", official="Republic of Bosnia and Herzegovina"),
    BL=dict(name="Saint Barthélemy", official=""),
    BY=dict(name="Belarus", official="Republic of Belarus"),
    BZ=dict(name="Belize", official=""),
    BM=dict(name="Bermuda", official=""),
    BO=dict(name="Bolivia, Plurinational State of", official="Plurinational State of Bolivia"),
    BR=dict(name="Brazil", official="Federative Republic of Brazil"),
    BB=dict(name="Barbados", official=""),
    BN=dict(name="Brunei Darussalam", official=""),
    BT=dict(name="Bhutan", official="Kingdom of Bhutan"),
    BV=dict(name="Bouvet Island", official=""),
    BW=dict(name="Botswana", official="Republic of Botswana"),
    CF=dict(name="Central African Republic", official=""),
    CA=dict(name="Canada", official=""),
    CC=dict(name="Cocos (Keeling) Islands", official=""),
    CH=dict(name="Switzerland", official="Swiss Confederation"),
    CL=dict(name="Chile", official="Republic of Chile"),
    CN=dict(name="China", official="People's Republic of China"),
    CI=dict(name="Côte d'Ivoire", official="Republic of Côte d'Ivoire"),
    CM=dict(name="Cameroon", official="Republic of Cameroon"),
    CD=dict(name="Congo, The Democratic Republic of the", official=""),
    CG=dict(name="Congo", official="Republic of the Congo"),
    CK=dict(name="Cook Islands", official=""),
    CO=dict(name="Colombia", official="Republic of Colombia"),
    KM=dict(name="Comoros", official="Union of the Comoros"),
    CV=dict(name="Cabo Verde", official="Republic of Cabo Verde"),
    CR=dict(name="Costa Rica", official="Republic of Costa Rica"),
    CU=dict(name="Cuba", official="Republic of Cuba"),
    CW=dict(name="Curaçao", official="Curaçao"),
    CX=dict(name="Christmas Island", official=""),
    KY=dict(name="Cayman Islands", official=""),
    CY=dict(name="Cyprus", official="Republic of Cyprus"),
    CZ=dict(name="Czechia", official="Czech Republic"),
    DE=dict(name="Germany", official="Federal Republic of Germany"),
    DJ=dict(name="Djibouti", official="Republic of Djibouti"),
    DM=dict(name="Dominica", official="Commonwealth of Dominica"),
    DK=dict(name="Denmark", official="Kingdom of Denmark"),
    DO=dict(name="Dominican Republic", official=""),
    DZ=dict(name="Algeria", official="People's Democratic Republic of Algeria"),
    EC=dict(name="Ecuador", official="Republic of Ecuador"),
    EG=dict(name="Egypt", official="Arab Republic of Egypt"),
    ER=dict(name="Eritrea", official="the State of Eritrea"),
    EH=dict(name="Western Sahara", official=""),
    ES=dict(name="Spain", official="Kingdom of Spain"),
    EE=dict(name="Estonia", official="Republic of Estonia"),
    ET=dict(name="Ethiopia", official="Federal Democratic Republic of Ethiopia"),
    FI=dict(name="Finland", official="Republic of Finland"),
    FJ=dict(name="Fiji", official="Republic of Fiji"),
    FK=dict(name="Falkland Islands (Malvinas)", official=""),
    FR=dict(name="France", official="French Republic"),
    FO=dict(name="Faroe Islands", official=""),
    FM=dict(name="Micronesia, Federated States of", official="Federated States of Micronesia"),
    GA=dict(name="Gabon", official="Gabonese Republic"),
    GB=dict(name="United Kingdom", official="United Kingdom of Great Britain and Northern Ireland"),
    GE=dict(name="Georgia", official=""),
    GG=dict(name="Guernsey", official=""),
    GH=dict(name="Ghana", official="Republic of Ghana"),
    GI=dict(name="Gibraltar", official=""),
    GN=dict(name="Guinea", official="Republic of Guinea"),
    GP=dict(name="Guadeloupe", official=""),
    GM=dict(name="Gambia", official="Republic of the Gambia"),
    GW=dict(name="Guinea-Bissau", official="Republic of Guinea-Bissau"),
    GQ=dict(name="Equatorial Guinea", official="Republic of Equatorial Guinea"),
    GR=dict(name="Greece", official="Hellenic Republic"),
    GD=dict(name="Grenada", official=""),
    GL=dict(name="Greenland", official=""),
    GT=dict(name="Guatemala", official="Republic of Guatemala"),
    GF=dict(name="French Guiana", official=""),
    GU=dict(name="Guam", official=""),
    GY=dict(name="Guyana", official="Republic of Guyana"),
    HK=dict(name="Hong Kong", official="Hong Kong Special Administrative Region of China"),
    HM=dict(name="Heard Island and McDonald Islands", official=""),
    HN=dict(name="Honduras", official="Republic of Honduras"),
    HR=dict(name="Croatia", official="Republic of Croatia"),
    HT=dict(name="Haiti", official="Republic of Haiti"),
    HU=dict(name="Hungary", official="Hungary"),
    ID=dict(name="Indonesia", official="Republic of Indonesia"),
    IM=dict(name="Isle of Man", official=""),
    IN=dict(name="India", official="Republic of India"),
    IO=dict(name="British Indian Ocean Territory", official=""),
    IE=dict(name="Ireland", official=""),
    IR=dict(name="Iran, Islamic Republic of", official="Islamic Republic of Iran"),
    IQ=dict(name="Iraq", official="Republic of Iraq"),
    IS=dict(name="Iceland", official="Republic of Iceland"),
    IL=dict(name="Israel", official="State of Israel"),
    IT=dict(name="Italy", official="Italian Republic"),
    JM=dict(name="Jamaica", official=""),
    JE=dict(name="Jersey", official=""),
    JO=dict(name="Jordan", official="Hashemite Kingdom of Jordan"),
    JP=dict(name="Japan", official=""),
    KZ=dict(name="Kazakhstan", official="Republic of Kazakhstan"),
    KE=dict(name="Kenya", official="Republic of Kenya"),
    KG=dict(name="Kyrgyzstan", official="Kyrgyz Republic"),
    KH=dict(name="Cambodia", official="Kingdom of Cambodia"),
    KI=dict(name="Kiribati", official="Republic of Kiribati"),
    KN=dict(name="Saint Kitts and Nevis", official=""),
    KR=dict(name="Korea, Republic of", official=""),
    KW=dict(name="Kuwait", official="State of Kuwait"),
    LA=dict(name="Lao People's Democratic Republic", official=""),
    LB=dict(name="Lebanon", official="Lebanese Republic"),
    LR=dict(name="Liberia", official="Republic of Liberia"),
    LY=dict(name="Libya", official="Libya"),
    LC=dict(name="Saint Lucia", official=""),
    LI=dict(name="Liechtenstein", official="Principality of Liechtenstein"),
    LK=dict(name="Sri Lanka", official="Democratic Socialist Republic of Sri Lanka"),
    LS=dict(name="Lesotho", official="Kingdom of Lesotho"),
    LT=dict(name="Lithuania", official="Republic of Lithuania"),
    LU=dict(name="Luxembourg", official="Grand Duchy of Luxembourg"),
    LV=dict(name="Latvia", official="Republic of Latvia"),
    MO=dict(name="Macao", official="Macao Special Administrative Region of China"),
    MF=dict(name="Saint Martin (French part)", official=""),
    MA=dict(name="Morocco", official="Kingdom of Morocco"),
    MC=dict(name="Monaco", official="Principality of Monaco"),
    MD=dict(name="Moldova, Republic of", official="Republic of Moldova"),
    MG=dict(name="Madagascar", official="Republic of Madagascar"),
    MV=dict(name="Maldives", official="Republic of Maldives"),
    MX=dict(name="Mexico", official="United Mexican States"),
    MH=dict(name="Marshall Islands", official="Republic of the Marshall Islands"),
    MK=dict(name="North Macedonia", official="Republic of North Macedonia"),
    ML=dict(name="Mali", official="Republic of Mali"),
    MT=dict(name="Malta", official="Republic of Malta"),
    MM=dict(name="Myanmar", official="Republic of Myanmar"),
    ME=dict(name="Montenegro", official="Montenegro"),
    MN=dict(name="Mongolia", official=""),
    MP=dict(name="Northern Mariana Islands", official="Commonwealth of the Northern Mariana Islands"),
    MZ=dict(name="Mozambique", official="Republic of Mozambique"),
    MR=dict(name="Mauritania", official="Islamic Republic of Mauritania"),
    MS=dict(name="Montserrat", official=""),
    MQ=dict(name="Martinique", official=""),
    MU=dict(name="Mauritius", official="Republic of Mauritius"),
    MW=dict(name="Malawi", official="Republic of Malawi"),
    MY=dict(name="Malaysia", official=""),
    YT=dict(name="Mayotte", official=""),
    NA=dict(name="Namibia", official="Republic of Namibia"),
    NC=dict(name="New Caledonia", official=""),
    NE=dict(name="Niger", official="Republic of the Niger"),
    NF=dict(name="Norfolk Island", official=""),
    NG=dict(name="Nigeria", official="Federal Republic of Nigeria"),
    NI=dict(name="Nicaragua", official="Republic of Nicaragua"),
    NU=dict(name="Niue", official="Niue"),
    NL=dict(name="Netherlands", official="Kingdom of the Netherlands"),
    NO=dict(name="Norway", official="Kingdom of Norway"),
    NP=dict(name="Nepal", official="Federal Democratic Republic of Nepal"),
    NR=dict(name="Nauru", official="Republic of Nauru"),
    NZ=dict(name="New Zealand", official=""),
    OM=dict(name="Oman", official="Sultanate of Oman"),
    PK=dict(name="Pakistan", official="Islamic Republic of Pakistan"),
    PA=dict(name="Panama", official="Republic of Panama"),
    PN=dict(name="Pitcairn", official=""),
    PE=dict(name="Peru", official="Republic of Peru"),
    PH=dict(name="Philippines", official="Republic of the Philippines"),
    PW=dict(name="Palau", official="Republic of Palau"),
    PG=dict(name="Papua New Guinea", official="Independent State of Papua New Guinea"),
    PL=dict(name="Poland", official="Republic of Poland"),
    PR=dict(name="Puerto Rico", official=""),
    KP=dict(name="Korea, Democratic People's Republic of", official="Democratic People's Republic of Korea"),
    PT=dict(name="Portugal", official="Portuguese Republic"),
    PY=dict(name="Paraguay", official="Republic of Paraguay"),
    PS=dict(name="Palestine, State of", official="the State of Palestine"),
    PF=dict(name="French Polynesia", official=""),
    QA=dict(name="Qatar", official="State of Qatar"),
    RE=dict(name="Réunion", official=""),
    RO=dict(name="Romania", official=""),
    RU=dict(name="Russian Federation", official=""),
    RW=dict(name="Rwanda", official="Rwandese Republic"),
    SA=dict(name="Saudi Arabia", official="Kingdom of Saudi Arabia"),
    SD=dict(name="Sudan", official="Republic of the Sudan"),
    SN=dict(name="Senegal", official="Republic of Senegal"),
    SG=dict(name="Singapore", official="Republic of Singapore"),
    GS=dict(name="South Georgia and the South Sandwich Islands", official=""),
    SH=dict(name="Saint Helena, Ascension and Tristan da Cunha", official=""),
    SJ=dict(name="Svalbard and Jan Mayen", official=""),
    SB=dict(name="Solomon Islands", official=""),
    SL=dict(name="Sierra Leone", official="Republic of Sierra Leone"),
    SV=dict(name="El Salvador", official="Republic of El Salvador"),
    SM=dict(name="San Marino", official="Republic of San Marino"),
    SO=dict(name="Somalia", official="Federal Republic of Somalia"),
    PM=dict(name="Saint Pierre and Miquelon", official=""),
    RS=dict(name="Serbia", official="Republic of Serbia"),
    SS=dict(name="South Sudan", official="Republic of South Sudan"),
    ST=dict(name="Sao Tome and Principe", official="Democratic Republic of Sao Tome and Principe"),
    SR=dict(name="Suriname", official="Republic of Suriname"),
    SK=dict(name="Slovakia", official="Slovak Republic"),
    SI=dict(name="Slovenia", official="Republic of Slovenia"),
    SE=dict(name="Sweden", official="Kingdom of Sweden"),
    SZ=dict(name="Eswatini", official="Kingdom of Eswatini"),
    SX=dict(name="Sint Maarten (Dutch part)", official="Sint Maarten (Dutch part)"),
    SC=dict(name="Seychelles", official="Republic of Seychelles"),
    SY=dict(name="Syrian Arab Republic", official=""),
    TC=dict(name="Turks and Caicos Islands", official=""),
    TD=dict(name="Chad", official="Republic of Chad"),
    TG=dict(name="Togo", official="Togolese Republic"),
    TH=dict(name="Thailand", official="Kingdom of Thailand"),
    TJ=dict(name="Tajikistan", official="Republic of Tajikistan"),
    TK=dict(name="Tokelau", official=""),
    TM=dict(name="Turkmenistan", official=""),
    TL=dict(name="Timor-Leste", official="Democratic Republic of Timor-Leste"),
    TO=dict(name="Tonga", official="Kingdom of Tonga"),
    TT=dict(name="Trinidad and Tobago", official="Republic of Trinidad and Tobago"),
    TN=dict(name="Tunisia", official="Republic of Tunisia"),
    TR=dict(name="Turkey", official="Republic of Turkey"),
    TV=dict(name="Tuvalu", official=""),
    TW=dict(name="Taiwan, Province of China", official="Taiwan, Province of China"),
    TZ=dict(name="Tanzania, United Republic of", official="United Republic of Tanzania"),
    UG=dict(name="Uganda", official="Republic of Uganda"),
    UA=dict(name="Ukraine", official=""),
    UM=dict(name="United States Minor Outlying Islands", official=""),
    UY=dict(name="Uruguay", official="Eastern Republic of Uruguay"),
    US=dict(name="United States", official="United States of America"),
    UZ=dict(name="Uzbekistan", official="Republic of Uzbekistan"),
    VA=dict(name="Holy See (Vatican City State)", official=""),
    VC=dict(name="Saint Vincent and the Grenadines", official=""),
    VE=dict(name="Venezuela, Bolivarian Republic of", official="Bolivarian Republic of Venezuela"),
    VG=dict(name="Virgin Islands, British", official="British Virgin Islands"),
    VI=dict(name="Virgin Islands, U.S.", official="Virgin Islands of the United States"),
    VN=dict(name="Viet Nam", official="Socialist Republic of Viet Nam"),
    VU=dict(name="Vanuatu", official="Republic of Vanuatu"),
    WF=dict(name="Wallis and Futuna", official=""),
    WS=dict(name="Samoa", official="Independent State of Samoa"),
    YE=dict(name="Yemen", official="Republic of Yemen"),
    ZA=dict(name="South Africa", official="Republic of South Africa"),
    ZM=dict(name="Zambia", official="Republic of Zambia"),
    ZW=dict(name="Zimbabwe", official="Republic of Zimbabwe"),
)
# ISO 3166-1-derived mapping (end)


def lookup(args):
    value = args.get("value")
    if not isinstance(value, str) or not value:
        raise ValueError("please provide a text value")

    data = COUNTRIES.get(value.upper())
    if not data:
        return value

    return data.get("name")


def main(args):
    try:
        return_results(lookup(args))
    except Exception as e:
        return_error(f"Failed to execute CyrenCountryLookup. Error: {str(e)}")


if __name__ in ("__main__", "__builtin__", "builtins"):
    main(demisto.args())
