import whois
import json


w = whois.whois("idf.gov.il")
# with open ('/Users/azonenfeld/dev/demisto/content/Packs/Whois/Integrations/Whois/b.json', 'w') as f:
#     f.write(w.text)
# print((dict(w.items())))
print(w)


dir = [
    "__class__",
    "__class_getitem__",
    "__contains__",
    "__delattr__",
    "__delitem__",
    "__dict__",
    "__dir__",
    "__doc__",
    "__eq__",
    "__format__",
    "__ge__",
    "__getattr__",
    "__getattribute__",
    "__getitem__",
    "__getstate__",
    "__gt__",
    "__hash__",
    "__init__",
    "__init_subclass__",
    "__ior__",
    "__iter__",
    "__le__",
    "__len__",
    "__lt__",
    "__module__",
    "__ne__",
    "__new__",
    "__or__",
    "__reduce__",
    "__reduce_ex__",
    "__repr__",
    "__reversed__",
    "__ror__",
    "__setattr__",
    "__setitem__",
    "__setstate__",
    "__sizeof__",
    "__str__",
    "__subclasshook__",
    "__weakref__",
    "_preprocess",
    "_regex",
    "clear",
    "copy",
    "dayfirst",
    "domain",
    "fromkeys",
    "get",
    "items",
    "keys",
    "load",
    "parse",
    "pop",
    "popitem",
    "setdefault",
    "text",
    "update",
    "values",
    "yearfirst",
]
