/** Test Plan – data module. Edit this file to add tests, setups or categories. */

/**
 * CONFIG_LISTS
 * Maps a named-range key -> array of allowed string values (dropdown vocabulary).
 * build.gs creates one named range per key and uses it for data-validation.
 * To add a new dropdown value, append it to the relevant array.
 */
const CONFIG_LISTS = {
  Ticket: ['CIAC-17084', 'CIAC-17085', 'CIAC-17086', 'CIAC-17274'],
  Active: ['Active', 'Deprecated'],
  Feature: ['Derived Packs', 'Release Notes', 'Notification Center', 'CSP BC Validation', 'Common-Base'],
  Tenant: ['Marketplace', 'Managed', 'Connectus', 'Multi', 'CI'],
  Phase: ['Pre-Optin', 'During-Optin', 'Post-Optin', 'Post-Optin + New Version', 'N-A'],
  PackState: ['Installed+Instance', 'Installed-NoInstance', 'Not-Installed', 'N-A'],
  PackType: ['Regular', 'Partner', 'Tightly-Only', 'Loosely-Only', 'COOC', 'Agentix', 'Autonomous', 'Base', 'Any', 'N-A'],
  Coupling: ['Tightly', 'Loosely', 'Both', 'N-A'],
  TestType: ['Functional', 'UI', 'Regression', 'Negative', 'Infra-CI'],
  Priority: ['P0', 'P1', 'P2'],
  Suite: ['Smoke', 'Full'],
  VerificationMethod: ['UI', 'Tenant Logs', 'API', 'Build Artifact', 'Bucket'],
  Automatable: ['Yes', 'No', 'Partial'],
  RunStatus: ['Not Run', 'In Progress', 'Pass', 'Fail', 'Blocked', 'Skipped', 'N-A'],
  SetupType: ['Build', 'PR', 'Code+Build', 'Manual'],
  SetupStatus: ['Pending', 'In Progress', 'Done', 'Failed'],
  BugSeverity: ['Critical', 'High', 'Medium', 'Low'],
  BugStatus: ['Open', 'In Progress', 'Fixed', 'Verified', "Won't Fix"]
};

/** Base URL used by build.gs to build HYPERLINK formulas for the Ticket column. */
const JIRA_BASE_URL = 'https://jira-hq.paloaltonetworks.local/browse/';

/**
 * SETUPS
 * Column order (8 columns):
 * [0] Setup ID
 * [1] Title
 * [2] Type              -> CONFIG_LISTS.SetupType
 * [3] Description
 * [4] Deployment Config
 * [5] Depends On        -> another Setup ID, or '' when independent
 * [6] Build/Bucket      -> filled in manually once the build/bucket exists
 * [7] Status            -> CONFIG_LISTS.SetupStatus
 */
const SETUPS = [
  [
    'SETUP-01',
    'Full derived-packs build + all packs on P1',
    'Build',
    'Run a build that creates the full new Connectus feature (derived packs) in the bucket. Bump versions for: regular packs, partner packs, tightly-coupled-only packs, loosely-coupled-only packs, COOC packs, Agentix packs, Autonomous packs.',
    'All packs defined in the deployment file on P1 with the current version',
    '',
    '',
    'Pending'
  ],
  [
    'SETUP-02',
    'Build on top of SETUP-01 bucket, no deployment update',
    'Build',
    'Run a build on the bucket produced by SETUP-01 (all derived packs already exist), without defining the deployment with the new versions.',
    'None',
    'SETUP-01',
    '',
    'Pending'
  ],
  [
    'SETUP-03',
    'Breaking functionality change in Base + build',
    'Code+Build',
    'Change basic functionality in the Base pack so that every content item consumes it, then run a build.',
    '',
    'SETUP-01',
    '',
    'Pending'
  ],
  [
    'SETUP-04',
    'PR with breaking CSP change for integrations',
    'PR',
    'Open a PR that changes CSP with a breaking change affecting integrations.',
    '',
    '',
    '',
    'Pending'
  ],
  [
    'SETUP-05',
    'PR with breaking CSP change inside a nested function',
    'PR',
    'Open a PR whose CSP breaking change is located in a function inside another function.',
    '',
    '',
    '',
    'Pending'
  ],
  [
    'SETUP-06',
    'PR with a non-breaking CSP change',
    'PR',
    'Open a PR that changes CSP with a change that is not breaking at all.',
    '',
    '',
    '',
    'Pending'
  ],
  [
    'SETUP-07',
    'PR with no CSP change at all',
    'PR',
    'Open a PR that does not touch CSP at all.',
    '',
    '',
    '',
    'Pending'
  ]
];

/**
 * TEST_CASES
 * Column order (21 columns):
 * [0]  ID
 * [1]  Ticket              -> CONFIG_LISTS.Ticket
 * [2]  Title
 * [3]  Active              -> CONFIG_LISTS.Active
 * [4]  Feature             -> CONFIG_LISTS.Feature
 * [5]  Tenant              -> CONFIG_LISTS.Tenant
 * [6]  Tenant Scope        -> free text, filled only when Tenant = 'Multi'
 * [7]  Phase               -> CONFIG_LISTS.Phase
 * [8]  Pack State          -> CONFIG_LISTS.PackState
 * [9]  Pack Type           -> CONFIG_LISTS.PackType
 * [10] Coupling            -> CONFIG_LISTS.Coupling
 * [11] Test Type           -> CONFIG_LISTS.TestType
 * [12] Priority            -> CONFIG_LISTS.Priority
 * [13] Suite               -> CONFIG_LISTS.Suite
 * [14] Setup Ref           -> Setup ID from SETUPS
 * [15] Preconditions       -> '' when nothing beyond the setup is required
 * [16] Steps               -> numbered, newline-separated ('\n')
 * [17] Expected Result
 * [18] Verification Method -> CONFIG_LISTS.VerificationMethod
 * [19] Test Data / Packs
 * [20] Automatable         -> CONFIG_LISTS.Automatable
 */
const TEST_CASES = [
  // ---------------------------------------------------------------------------
  // CIAC-17084 – Derived Packs – Group A: Pre-Optin, Installed+Instance
  // ---------------------------------------------------------------------------
  [
    'DP-001',
    'CIAC-17084',
    'Regular packs version content identical to pre-bump',
    'Active',
    'Derived Packs',
    'Marketplace',
    '',
    'Pre-Optin',
    'Installed+Instance',
    'Regular',
    'N-A',
    'UI',
    'P0',
    'Smoke',
    'SETUP-01',
    '',
    '1. Record the pack content of a regular pack before the version bump\n2. Open Marketplace on the tenant\n3. Search for the same regular pack after the build\n4. Open the pack page and compare the content items list',
    'The pack contains exactly the same as before the version bump in Marketplace, including the display of all content items.',
    'UI',
    '',
    'No'
  ],
  [
    'DP-002',
    'CIAC-17084',
    'Partner packs version content identical to pre-bump',
    'Active',
    'Derived Packs',
    'Marketplace',
    '',
    'Pre-Optin',
    'Installed+Instance',
    'Partner',
    'N-A',
    'UI',
    'P1',
    'Full',
    'SETUP-01',
    '',
    '1. Record the pack content of a partner pack before the version bump\n2. Open Marketplace on the tenant\n3. Search for the same partner pack after the build\n4. Open the pack page and compare the content items list',
    'The pack contains exactly the same as before the version bump in Marketplace, including the display of all content items.',
    'UI',
    '',
    'No'
  ],
  [
    'DP-003',
    'CIAC-17084',
    'Tightly-coupled-only packs version content identical to pre-bump',
    'Active',
    'Derived Packs',
    'Marketplace',
    '',
    'Pre-Optin',
    'Installed+Instance',
    'Tightly-Only',
    'Tightly',
    'UI',
    'P0',
    'Smoke',
    'SETUP-01',
    '',
    '1. Record the pack content of a tightly-coupled-only pack before the version bump\n2. Open Marketplace on the tenant\n3. Search for the same pack after the build\n4. Open the pack page and compare the content items list',
    'The pack contains exactly the same as before the version bump in Marketplace, including the display of all content items.',
    'UI',
    '',
    'No'
  ],
  [
    'DP-004',
    'CIAC-17084',
    'COOC packs hidden in Marketplace and installed via Managed',
    'Active',
    'Derived Packs',
    'Managed',
    '',
    'Pre-Optin',
    'Installed+Instance',
    'COOC',
    'N-A',
    'Functional',
    'P0',
    'Smoke',
    'SETUP-01',
    '',
    '1. Open Marketplace on the tenant and search for the COOC pack\n2. Verify the pack is not listed\n3. Open the tenant logs and look for the managed installation of the pack\n4. Verify the installed pack id and its content items',
    'The pack does not appear in Marketplace at all, and it is installed via Managed so the pack id carries the `Managed` suffix and all content items exist – verified through the tenant logs showing the version was installed.',
    'Tenant Logs',
    '',
    'Partial'
  ],
  [
    'DP-005',
    'CIAC-17084',
    'Agentix packs behave as before',
    'Active',
    'Derived Packs',
    'Managed',
    '',
    'Pre-Optin',
    'Installed+Instance',
    'Agentix',
    'N-A',
    'Regression',
    'P1',
    'Full',
    'SETUP-01',
    '',
    '1. Open the Agentix pack on the tenant\n2. Compare the pack version and name to the state before the build\n3. Compare the content items names and behavior',
    'The Agentix pack behaves exactly as it did until now – version, names, etc.',
    'UI',
    '',
    'No'
  ],

  // ---------------------------------------------------------------------------
  // CIAC-17084 – Derived Packs – Group B: During-Optin, Installed+Instance
  // ---------------------------------------------------------------------------
  [
    'DP-006',
    'CIAC-17084',
    'Basic opt-in flow installs all derived packs',
    'Active',
    'Derived Packs',
    'Connectus',
    '',
    'During-Optin',
    'Installed+Instance',
    'Any',
    'Both',
    'Functional',
    'P0',
    'Smoke',
    'SETUP-01',
    '',
    '1. Open Connectus and start the opt-in process for a connector\n2. Complete the opt-in flow\n3. Open the tenant logs and list the packs installed by the flow',
    'For every connector that goes through the opt-in process, all derived packs are installed (verified in the tenant logs).',
    'Tenant Logs',
    '',
    'Partial'
  ],
  [
    'DP-007',
    'CIAC-17084',
    'Opt-in screen lists all packs connected to the connector',
    'Active',
    'Derived Packs',
    'Connectus',
    '',
    'During-Optin',
    'Installed+Instance',
    'Any',
    'Both',
    'UI',
    'P1',
    'Full',
    'SETUP-01',
    '',
    '1. Open Connectus and start the opt-in process for a connector\n2. Review the packs list displayed on the opt-in screen\n3. Compare it to the packs connected to that connector',
    'All packs the connector is connected to are displayed during the opt-in process.',
    'UI',
    '',
    'No'
  ],

  // ---------------------------------------------------------------------------
  // CIAC-17084 – Derived Packs – Group C: Post-Optin, Installed+Instance
  // ---------------------------------------------------------------------------
  [
    'DP-008',
    'CIAC-17084',
    'Connector shows tightly-coupled content items only',
    'Active',
    'Derived Packs',
    'Connectus',
    '',
    'Post-Optin',
    'Installed+Instance',
    'Any',
    'Tightly',
    'UI',
    'P0',
    'Smoke',
    'SETUP-01',
    'The connector completed the opt-in process',
    '1. Open Connectus and select the opted-in connector\n2. Open the content items list of the connector\n3. Compare the list to the tightly-coupled and loosely-coupled items of the related packs',
    'The connector displays all the tightly-coupled content items related to it, and not the loosely-coupled ones.',
    'UI',
    '',
    'No'
  ],
  [
    'DP-009',
    'CIAC-17084',
    'Only loosely-coupled shown in Marketplace before new version install',
    'Active',
    'Derived Packs',
    'Multi',
    'Connectus & Marketplace',
    'Post-Optin',
    'Installed+Instance',
    'Regular',
    'Loosely',
    'UI',
    'P0',
    'Smoke',
    'SETUP-01',
    'The connector completed the opt-in process and the new pack version was not installed yet',
    '1. Complete the opt-in process in Connectus for the pack\n2. Open Marketplace on the tenant\n3. Open the opted-in pack page without installing the new version\n4. Review the displayed content items',
    'In Marketplace, packs that were opted-in display only the loosely-coupled content items – before the pack is installed.',
    'UI',
    '',
    'No'
  ],
  [
    'DP-010',
    'CIAC-17084',
    'Only loosely-coupled shown in Marketplace after new version install',
    'Active',
    'Derived Packs',
    'Multi',
    'Connectus & Marketplace',
    'Post-Optin + New Version',
    'Installed+Instance',
    'Regular',
    'Loosely',
    'UI',
    'P0',
    'Smoke',
    'SETUP-01',
    'The connector completed the opt-in process',
    '1. Complete the opt-in process in Connectus for the pack\n2. Open Marketplace on the tenant and install the new pack version\n3. Open the pack page\n4. Review the displayed content items',
    'In Marketplace, packs that were opted-in display only the loosely-coupled content items – after the pack is installed.',
    'UI',
    '',
    'No'
  ],
  [
    'DP-011',
    'CIAC-17084',
    'Tightly-only pack is not shown in Marketplace',
    'Active',
    'Derived Packs',
    'Multi',
    'Connectus & Marketplace',
    'Post-Optin',
    'Installed+Instance',
    'Tightly-Only',
    'Tightly',
    'Negative',
    'P0',
    'Smoke',
    'SETUP-01',
    'The connector completed the opt-in process',
    '1. Complete the opt-in process in Connectus for a pack containing only tightly-coupled items\n2. Open Marketplace on the tenant\n3. Search for that pack by name',
    'A pack containing only tightly-coupled items is not displayed in Marketplace at all.',
    'UI',
    '',
    'No'
  ],

  // ---------------------------------------------------------------------------
  // CIAC-17084 – Derived Packs – Group D: SETUP-02, Post-Optin, Marketplace
  // ---------------------------------------------------------------------------
  [
    'DP-012',
    'CIAC-17084',
    'Opted-in packs do not show the new versions',
    'Active',
    'Derived Packs',
    'Marketplace',
    '',
    'Post-Optin',
    'Installed+Instance',
    'Any',
    'Both',
    'Negative',
    'P0',
    'Smoke',
    'SETUP-02',
    'The packs were opted-in through Connectus',
    '1. Open Marketplace on the tenant\n2. Open an opted-in pack page\n3. Check the versions list of the pack',
    'The new versions are not displayed in Marketplace for opted-in packs, because the new versions were not installed through Connectus.',
    'UI',
    '',
    'No'
  ],
  [
    'DP-013',
    'CIAC-17084',
    'Non-opted-in packs do show the new versions',
    'Active',
    'Derived Packs',
    'Marketplace',
    '',
    'Post-Optin',
    'Installed+Instance',
    'Any',
    'Both',
    'Functional',
    'P1',
    'Full',
    'SETUP-02',
    'The packs were not opted-in through Connectus',
    '1. Open Marketplace on the tenant\n2. Open a pack that was not opted-in\n3. Check the versions list of the pack',
    'The new versions are displayed in Marketplace for packs that were not opted-in.',
    'UI',
    '',
    'No'
  ],

  // ---------------------------------------------------------------------------
  // CIAC-17084 – Derived Packs – Group E: Not-Installed packs
  // ---------------------------------------------------------------------------
  [
    'DP-014',
    'CIAC-17084',
    'Tightly-coupled never shown for non-installed packs',
    'Active',
    'Derived Packs',
    'Marketplace',
    '',
    'N-A',
    'Not-Installed',
    'Any',
    'Tightly',
    'Negative',
    'P1',
    'Full',
    'SETUP-01',
    '',
    '1. Open Marketplace on the tenant\n2. Search for a pack that is not installed\n3. Open the pack page and review the content items list',
    'For packs that are not installed through Marketplace, the tightly-coupled items are not displayed at all in Marketplace.',
    'UI',
    '',
    'No'
  ],
  [
    'DP-015',
    'CIAC-17084',
    'Pack with no loosely-coupled items is fully hidden',
    'Active',
    'Derived Packs',
    'Marketplace',
    '',
    'N-A',
    'Not-Installed',
    'Tightly-Only',
    'Tightly',
    'Negative',
    'P1',
    'Full',
    'SETUP-01',
    '',
    '1. Open Marketplace on the tenant\n2. Search for a pack that has no loosely-coupled items\n3. Verify the search results',
    'A pack that has no loosely-coupled items is not displayed in Marketplace at all.',
    'UI',
    '',
    'No'
  ],

  // ---------------------------------------------------------------------------
  // CIAC-17084 – Derived Packs – Group F: Installed-NoInstance
  // ---------------------------------------------------------------------------
  [
    'DP-016',
    'CIAC-17084',
    'Installed-without-instance packs behave like non-installed',
    'Active',
    'Derived Packs',
    'Marketplace',
    '',
    'N-A',
    'Installed-NoInstance',
    'Any',
    'Both',
    'Regression',
    'P2',
    'Full',
    'SETUP-01',
    'The pack is installed on the tenant but has no configured instance',
    '1. Install a pack without configuring an instance\n2. Open Marketplace on the tenant\n3. Open the pack page and review the displayed content items\n4. Compare the display to a pack that is not installed at all',
    'In Marketplace it behaves exactly like packs that are not installed at all.',
    'UI',
    '',
    'No'
  ],

  // ---------------------------------------------------------------------------
  // CIAC-17084 – Common-Base – SETUP-03
  // General check of the `common` feature, before updating the Base version
  // in Marketplace.
  // ---------------------------------------------------------------------------
  [
    'CMN-001',
    'CIAC-17084',
    'CommonManaged installed via Managed and decoupled from Base',
    'Active',
    'Common-Base',
    'Managed',
    '',
    'N-A',
    'Installed+Instance',
    'Base',
    'N-A',
    'Functional',
    'P0',
    'Smoke',
    'SETUP-03',
    '',
    '1. Trigger the managed content installation on the tenant\n2. Open the tenant logs and locate the CommonManaged pack installation\n3. Verify the CommonManaged pack has no dependency or link to the Base pack',
    'The CommonManaged pack is installed through Managed and has no connection whatsoever to the Base pack (the origin of the files).',
    'Tenant Logs',
    '',
    'Partial'
  ],
  [
    'CMN-002',
    'CIAC-17084',
    'CommonManaged scripts carry the Managed suffix',
    'Active',
    'Common-Base',
    'Managed',
    '',
    'N-A',
    'Installed+Instance',
    'Base',
    'N-A',
    'UI',
    'P1',
    'Full',
    'SETUP-03',
    '',
    '1. Open the CommonManaged pack on the tenant\n2. Open the scripts list of the pack\n3. Review the script names',
    'The scripts under CommonManaged carry the `Managed` suffix.',
    'UI',
    '',
    'No'
  ],
  [
    'CMN-003',
    'CIAC-17084',
    'Managed-installed content items work with the managed CSP',
    'Active',
    'Common-Base',
    'Multi',
    'Managed & Common & Connectus',
    'N-A',
    'Installed+Instance',
    'Base',
    'N-A',
    'Functional',
    'P0',
    'Smoke',
    'SETUP-03',
    '',
    '1. Install content items through Managed\n2. Run a content item that consumes CSP\n3. Verify the CSP version used by the run\n4. Verify the run completes successfully',
    'Every content item installed from Managed works with the CSP that is installed through Managed.',
    'UI',
    '',
    'No'
  ],
  [
    'CMN-004',
    'CIAC-17084',
    'Marketplace-installed content items work with the Marketplace Base',
    'Active',
    'Common-Base',
    'Marketplace',
    '',
    'N-A',
    'Installed+Instance',
    'Base',
    'N-A',
    'Functional',
    'P0',
    'Smoke',
    'SETUP-03',
    '',
    '1. Install a pack from Marketplace on the tenant\n2. Run a content item from that pack that consumes the Base functionality\n3. Verify which Base version is used by the run',
    'Every content item installed from Marketplace works with the Base version installed through Marketplace, without the changes made in the new version.',
    'UI',
    '',
    'No'
  ],

  // ---------------------------------------------------------------------------
  // CIAC-17085 – Release Notes – Marketplace, SETUP-01, Installed+Instance
  // ---------------------------------------------------------------------------
  [
    'RN-001',
    'CIAC-17085',
    'RN unchanged for packs bumped before installation',
    'Active',
    'Release Notes',
    'Marketplace',
    '',
    'Pre-Optin',
    'Installed+Instance',
    'Any',
    'Both',
    'UI',
    'P0',
    'Smoke',
    'SETUP-01',
    'The pack version was bumped before the pack was installed',
    '1. Open Marketplace on the tenant\n2. Open a pack that was bumped before installation\n3. Open the release notes tab\n4. Compare the release notes to the state before the version bump',
    'The release notes are displayed exactly as before the version bump, including all content items.',
    'UI',
    '',
    'No'
  ],
  [
    'RN-002',
    'CIAC-17085',
    'RN unchanged for packs bumped after installation',
    'Active',
    'Release Notes',
    'Marketplace',
    '',
    'Pre-Optin',
    'Installed+Instance',
    'Any',
    'Both',
    'UI',
    'P1',
    'Full',
    'SETUP-01',
    'The pack was installed and only afterwards the version was bumped',
    '1. Install the pack on the tenant\n2. Run the build that bumps the pack version\n3. Open Marketplace and open the pack release notes tab\n4. Compare the release notes to the state before the version bump',
    'The release notes are displayed exactly as before the version bump, including all content items.',
    'UI',
    '',
    'No'
  ],
  [
    'RN-003',
    'CIAC-17085',
    'BC notes read from the legacy root-level field',
    'Active',
    'Release Notes',
    'Marketplace',
    '',
    'Pre-Optin',
    'Installed+Instance',
    'Any',
    'N-A',
    'UI',
    'P0',
    'Smoke',
    'SETUP-01',
    'The installed version contains a breaking change with `breakingChangesNotes` at the root of the BC file',
    '1. Open Marketplace on the tenant\n2. Install a version that contains a breaking change\n3. Open the release notes of that version\n4. Compare the displayed BC text to the BC file in the repo',
    'When installing a version that has a breaking change, the content of the BC file in the repo is displayed from the `breakingChangesNotes` field located at the root of the file (the old field).',
    'UI',
    '',
    'No'
  ],
  [
    'RN-004',
    'CIAC-17085',
    'RN limited to loosely-coupled items (bumped before install)',
    'Active',
    'Release Notes',
    'Marketplace',
    '',
    'Post-Optin',
    'Installed+Instance',
    'Any',
    'Loosely',
    'UI',
    'P0',
    'Smoke',
    'SETUP-01',
    'The pack was opted-in and its version was bumped before installation',
    '1. Complete the opt-in process for the pack\n2. Open Marketplace on the tenant\n3. Open the pack release notes tab\n4. Review which content items appear in the release notes',
    'The release notes are displayed only for the loosely-coupled content items.',
    'UI',
    '',
    'No'
  ],
  [
    'RN-005',
    'CIAC-17085',
    'RN limited to loosely-coupled items (bumped after install)',
    'Active',
    'Release Notes',
    'Marketplace',
    '',
    'Post-Optin',
    'Installed+Instance',
    'Any',
    'Loosely',
    'UI',
    'P1',
    'Full',
    'SETUP-01',
    'The pack was opted-in and installed, and only afterwards the version was bumped',
    '1. Complete the opt-in process and install the pack\n2. Run the build that bumps the pack version\n3. Open Marketplace and open the pack release notes tab\n4. Review which content items appear in the release notes',
    'The release notes are displayed only for the loosely-coupled content items.',
    'UI',
    '',
    'No'
  ],
  [
    'RN-006',
    'CIAC-17085',
    'BC notes read from the new force-update field',
    'Active',
    'Release Notes',
    'Marketplace',
    '',
    'Post-Optin',
    'Installed+Instance',
    'Any',
    'N-A',
    'UI',
    'P0',
    'Smoke',
    'SETUP-01',
    'The installed version contains a breaking change with `breakingChangesNotes` under the `force-update` field',
    '1. Complete the opt-in process for the pack\n2. Install a version that contains a breaking change\n3. Open the release notes of that version\n4. Compare the displayed BC text to the BC file in the repo',
    'When installing a version that has a breaking change, the content of the BC file in the repo is displayed from the `breakingChangesNotes` field located under the `force-update` field (the new field).',
    'UI',
    '',
    'No'
  ],

  // ---------------------------------------------------------------------------
  // CIAC-17086 – Notification Center – Managed, SETUP-01
  // All during/after installing a version through managed content.
  // ---------------------------------------------------------------------------
  [
    'NC-001',
    'CIAC-17086',
    'Notification on pack installation with the expected version',
    'Active',
    'Notification Center',
    'Managed',
    '',
    'N-A',
    'Installed+Instance',
    'Any',
    'N-A',
    'UI',
    'P0',
    'Smoke',
    'SETUP-01',
    '',
    '1. Install a pack version through managed content\n2. Open the notification center on the tenant\n3. Locate the installation notification\n4. Compare the version in the notification to the installed version',
    'A notification about the pack installation appears in the notification center with the expected version.',
    'UI',
    '',
    'No'
  ],
  [
    'NC-002',
    'CIAC-17086',
    '"More info" button in the installation notification opens a modal',
    'Active',
    'Notification Center',
    'Managed',
    '',
    'N-A',
    'Installed+Instance',
    'Any',
    'N-A',
    'UI',
    'P1',
    'Full',
    'SETUP-01',
    '',
    '1. Install a pack version through managed content\n2. Open the notification center on the tenant\n3. Locate the installation notification\n4. Click the `more info` button',
    'Clicking the `more info` button on the installation notification opens a modal.',
    'UI',
    '',
    'No'
  ],
  [
    'NC-003',
    'CIAC-17086',
    'Installation modal shows the changelog `releaseNotes` content',
    'Active',
    'Notification Center',
    'Managed',
    '',
    'N-A',
    'Installed+Instance',
    'Any',
    'N-A',
    'UI',
    'P0',
    'Smoke',
    'SETUP-01',
    '',
    '1. Install a pack version through managed content\n2. Open the notification center and locate the installation notification\n3. Click the `more info` button\n4. Compare the modal content to the changelog file of the installed version',
    'The modal opened by clicking `more info` in the notification center displays the content of the `releaseNotes` field from the changelog file.',
    'UI',
    '',
    'No'
  ],
  [
    'NC-004',
    'CIAC-17086',
    'Static BC notification appears in the notification center',
    'Active',
    'Notification Center',
    'Managed',
    '',
    'N-A',
    'Installed+Instance',
    'Any',
    'N-A',
    'UI',
    'P0',
    'Smoke',
    'SETUP-01',
    'The installed version contains a breaking change',
    '1. Install a version that contains a breaking change through managed content\n2. Open the notification center on the tenant\n3. Locate the breaking change notification',
    'A static breaking change notification appears in the notification center.',
    'UI',
    '',
    'No'
  ],
  [
    'NC-005',
    'CIAC-17086',
    '"More info" button on the BC notification opens a modal',
    'Active',
    'Notification Center',
    'Managed',
    '',
    'N-A',
    'Installed+Instance',
    'Any',
    'N-A',
    'UI',
    'P1',
    'Full',
    'SETUP-01',
    'The installed version contains a breaking change',
    '1. Install a version that contains a breaking change through managed content\n2. Open the notification center and locate the breaking change notification\n3. Click the `more info` button',
    'Clicking the `more info` button on the breaking change notification opens a modal.',
    'UI',
    '',
    'No'
  ],
  [
    'NC-006',
    'CIAC-17086',
    'BC notification modal shows the changelog `releaseNotice` content',
    'Active',
    'Notification Center',
    'Managed',
    '',
    'N-A',
    'Installed+Instance',
    'Any',
    'N-A',
    'UI',
    'P0',
    'Smoke',
    'SETUP-01',
    'The installed version contains a breaking change',
    '1. Install a version that contains a breaking change through managed content\n2. Open the notification center and locate the breaking change notification\n3. Click the `more info` button\n4. Compare the modal content to the changelog file of the installed version',
    'The modal opened from the breaking change notification displays the content of the `releaseNotice` field from the changelog file.',
    'UI',
    '',
    'No'
  ],
  [
    'NC-007',
    'CIAC-17086',
    'Static BC banner appears at the top of the page',
    'Active',
    'Notification Center',
    'Managed',
    '',
    'N-A',
    'Installed+Instance',
    'Any',
    'N-A',
    'UI',
    'P0',
    'Smoke',
    'SETUP-01',
    'The installed version contains a breaking change',
    '1. Install a version that contains a breaking change through managed content\n2. Open the tenant main page\n3. Review the top of the page',
    'A static breaking change banner appears at the top of the page.',
    'UI',
    '',
    'No'
  ],
  [
    'NC-008',
    'CIAC-17086',
    '"More info" button in the top banner opens a modal',
    'Active',
    'Notification Center',
    'Managed',
    '',
    'N-A',
    'Installed+Instance',
    'Any',
    'N-A',
    'UI',
    'P1',
    'Full',
    'SETUP-01',
    'The installed version contains a breaking change',
    '1. Install a version that contains a breaking change through managed content\n2. Open the tenant main page and locate the top banner\n3. Click the `more info` button in the banner',
    'Clicking the `more info` button in the top banner opens a modal.',
    'UI',
    '',
    'No'
  ],
  [
    'NC-009',
    'CIAC-17086',
    'Top-banner modal shows the changelog `releaseNotice` content',
    'Active',
    'Notification Center',
    'Managed',
    '',
    'N-A',
    'Installed+Instance',
    'Any',
    'N-A',
    'UI',
    'P0',
    'Smoke',
    'SETUP-01',
    'The installed version contains a breaking change',
    '1. Install a version that contains a breaking change through managed content\n2. Open the tenant main page and locate the top banner\n3. Click the `more info` button in the banner\n4. Compare the modal content to the changelog file of the installed version',
    'The modal opened from the top banner displays the content of the `releaseNotice` field from the changelog file.',
    'UI',
    '',
    'No'
  ],

  // ---------------------------------------------------------------------------
  // CIAC-17274 – CSP BC Validation – CI
  // ---------------------------------------------------------------------------
  [
    'CSP-001',
    'CIAC-17274',
    'Breaking integrations listed under the BC category',
    'Active',
    'CSP BC Validation',
    'CI',
    '',
    'N-A',
    'N-A',
    'N-A',
    'N-A',
    'Infra-CI',
    'P0',
    'Smoke',
    'SETUP-04',
    '',
    '1. Open the PR with the breaking CSP change\n2. Wait for the CSP validate job to finish\n3. Download the report artifact\n4. Review the integrations listed under the BC category',
    'All integrations that the change will break appear in the report under the BC category.',
    'Build Artifact',
    '',
    'Yes'
  ],
  [
    'CSP-002',
    'CIAC-17274',
    'Non-breaking integrations listed under safe',
    'Active',
    'CSP BC Validation',
    'CI',
    '',
    'N-A',
    'N-A',
    'N-A',
    'N-A',
    'Infra-CI',
    'P0',
    'Smoke',
    'SETUP-04',
    '',
    '1. Open the PR with the breaking CSP change\n2. Wait for the CSP validate job to finish\n3. Download the report artifact\n4. Review the integrations listed under the `safe` category',
    'Integrations the change does not break do not appear under the BC category but under `safe`.',
    'Build Artifact',
    '',
    'Yes'
  ],
  [
    'CSP-003',
    'CIAC-17274',
    'Unaffected integrations excluded from the report',
    'Active',
    'CSP BC Validation',
    'CI',
    '',
    'N-A',
    'N-A',
    'N-A',
    'N-A',
    'Infra-CI',
    'P1',
    'Full',
    'SETUP-04',
    '',
    '1. Open the PR with the breaking CSP change\n2. Wait for the CSP validate job to finish\n3. Download the report artifact\n4. Search the report for integrations that do not use the changed CSP code',
    'Integrations the change does not affect at all do not appear in the report at all.',
    'Build Artifact',
    '',
    'Yes'
  ],
  [
    'CSP-004',
    'CIAC-17274',
    'Non-integration content items using CSP behave the same',
    'Active',
    'CSP BC Validation',
    'CI',
    '',
    'N-A',
    'N-A',
    'N-A',
    'N-A',
    'Infra-CI',
    'P1',
    'Full',
    'SETUP-04',
    '',
    '1. Open the PR with the breaking CSP change\n2. Wait for the CSP validate job to finish\n3. Download the report artifact\n4. Review the scripts and other non-integration content items that use CSP',
    'A content item that is not an integration but uses CSP (e.g. a script) also behaves as expected for all the states checked for integrations.',
    'Build Artifact',
    '',
    'Yes'
  ],
  [
    'CSP-005',
    'CIAC-17274',
    'Nested-function breaking change detected identically',
    'Active',
    'CSP BC Validation',
    'CI',
    '',
    'N-A',
    'N-A',
    'N-A',
    'N-A',
    'Infra-CI',
    'P0',
    'Smoke',
    'SETUP-05',
    '',
    '1. Open the PR whose CSP breaking change is inside a nested function\n2. Wait for the CSP validate job to finish\n3. Download the report artifact\n4. Compare the report to the expected results of the regular breaking change scenario',
    'All the integration checks for a regular breaking change work the same way in this case.',
    'Build Artifact',
    '',
    'Yes'
  ],
  [
    'CSP-006',
    'CIAC-17274',
    'Report is empty for a non-breaking change',
    'Active',
    'CSP BC Validation',
    'CI',
    '',
    'N-A',
    'N-A',
    'N-A',
    'N-A',
    'Infra-CI',
    'P1',
    'Full',
    'SETUP-06',
    '',
    '1. Open the PR with the non-breaking CSP change\n2. Wait for the CSP validate job to finish\n3. Download the report artifact\n4. Review the report content',
    'The report does not contain any integration.',
    'Build Artifact',
    '',
    'Yes'
  ],
  [
    'CSP-007',
    'CIAC-17274',
    'CSP validate job exits immediately with no CSP change',
    'Active',
    'CSP BC Validation',
    'CI',
    '',
    'N-A',
    'N-A',
    'N-A',
    'N-A',
    'Infra-CI',
    'P2',
    'Full',
    'SETUP-07',
    '',
    '1. Open the PR that does not touch CSP at all\n2. Open the pipeline of the PR\n3. Review the CSP validate job status and duration',
    'The CSP validate job in the pipeline finishes immediately.',
    'Build Artifact',
    '',
    'Yes'
  ]
];
