{
  "openapi": "3.0.1",
  "info": {
    "title": "LGTM API specification",
    "description": "The REST API for LGTM provides data so that you can customize how you integrate LGTM analysis into your workflow. It includes the following resources:\n  * `/` ([API root](https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-API-root))&mdash;get version information or download the specification in OpenAPI format.\n  * `/projects` ([Projects](https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-Projects))&mdash;list projects, get a summary of the current status[...]",
    "version": "v1.0"
  },
  "servers": [
    {
      "url": "https://lgtm.com/api/v1.0"
    }
  ],
  "tags": [
    {
      "name": "API root",
      "description": "The `/` endpoints are used to get information about the API:\n  * [Get the API version number](https://lgtm.com/help/lgtm/api/api-v1#opIdgetVersion) for the LGTM server.\n  * [View the API specification](https://lgtm.com/help/lgtm/api/api-v1#opIdgetSpec) in [OpenAPI format](https://github.com/OAI/OpenAPI-Specification).\n"
    },
    {
      "name": "Projects",
      "description": "The `/projects` endpoints are used to interact with projects:\n  * [List the projects](https://lgtm.com/help/lgtm/api/api-v1#opIdgetProjects) available to the current user.\n  * Get the latest summary for a specific project [by identifier](https://lgtm.com/help/lgtm/api/api-v1#opIdgetProject), \n  or by [URL identifier](https://lgtm.com/help/lgtm/api/api-v1#opIdgetProjectByUrlIdentifier).\n  * LGTM administrators only, [add projects](https://lgtm.com/help/lgtm/api/api-v1#op[...]"
    },
    {
      "name": "Analyses",
      "description": "Most of the `/analyses` endpoints are used to retrieve the results of analyzing a commit:\n  * [Get the *analysis* identifier and results summary for the latest or a specific commit](https://lgtm.com/help/lgtm/api/api-v1#opIdgetAnalysisForCommit).\n  * [Get the *commit* identifier and results summary for a specific analysis](https://lgtm.com/help/lgtm/api/api-v1#opIdgetAnalysis).\n  * [Download the full results for a specific analysis](https://lgtm.com/help/lgtm/api/api-v1#[...]"
    },
    {
      "name": "Code reviews",
      "description": "The `/codereviews` endpoint is used to trigger a patch code review and request the results:\n  * [Trigger the review of a patch](https://lgtm.com/help/lgtm/api/api-v1#opIdrequestReview).\n  * [Get the results of a completed code review](https://lgtm.com/help/lgtm/api/api-v1#opIdgetCodeReview).\n"
    }
  ],
  "paths": {
    "/": {
      "get": {
        "tags": [
          "API root"
        ],
        "summary": "Version information",
        "description": "Get the version information of this API.",
        "operationId": "getVersion",
        "security": [
          {
            "access-token": []
          }
        ],
        "x-auth-mode": "UNRESTRICTED"
      }
    },
    "/openapi": {
      "get": {
        "tags": [
          "API root"
        ],
        "summary": "API specification",
        "description": "Get the specification of this API in [OpenAPI](https://github.com/OAI/OpenAPI-Specification) format. This endpoint does not require an access token. This makes it easier for you to use the specification with third-party tools.",
        "operationId": "getSpec",
        "x-auth-mode": "UNRESTRICTED"
      }
    },
    "/projects": {
      "get": {
        "tags": [
          "Projects"
        ],
        "summary": "List projects",
        "description": "List all the projects the current user has authorization to view. \n\nA maximum of 100 projects are returned in each response. When further results are available, the response includes the URL you need to request the next page of results.\n\nUse the optional parameter, `limit`, to change the number of results reported in each response (range of 1&mdash;100). If you supply an invalid value for this  parameter, the default value of 100 is used.\n\nWhen more than one page of[...]",
        "operationId": "getProjects",
        "security": [
          {
            "access-token": [
              "projects:read"
            ]
          }
        ],
        "x-auth-mode": "FILTERING"
      },
      "post": {
        "tags": [
          "Projects"
        ],
        "summary": "Add a project to LGTM",
        "description": "LGTM administrators can add a new project to LGTM by providing a repository URL. By default, LGTM tries to build and analyze the project in the same way as for projects added through the user interface. If at least one language is successfully analyzed, and the repository doesn't already exist on LGTM, a new project is created. If the project already exists but your API call triggers a successful analysis  of additional languages, LGTM adds those languages to the project.[...]",
        "operationId": "addProject",
        "security": [
          {
            "access-token": [
              "projects:write"
            ]
          }
        ],
        "x-auth-mode": "BINARY"
      }
    },
    "/projects/{project-id}": {
      "get": {
        "tags": [
          "Projects"
        ],
        "summary": "Get project by numeric identifier",
        "description": "Get the latest summary for a specific project using the numeric project identifier.\n\nTo find the LGTM identifier for a project, list all projects using the `/projects`  endpoint and look up the project by name. Alternatively, use the `/projects/{provider}/{org}/{name}` endpoint. If you have administration access, the project identifier is also displayed in  the administration page for the project.\n",
        "operationId": "getProject",
        "security": [
          {
            "access-token": [
              "projects:read"
            ]
          }
        ],
        "x-auth-mode": "BINARY"
      }
    },
    "/projects/{project-id}/settings/analysis-configuration": {
      "get": {
        "tags": [
          "Projects"
        ],
        "summary": "Get configuration for a project identified by numeric identifier",
        "description": "Get the latest configuration for a specific project using the numeric project identifier.",
        "operationId": "getProjectConfig",
        "security": [
          {
            "access-token": [
              "projects:read"
            ]
          }
        ],
        "x-auth-mode": "BINARY"
      }
    },
    "/projects/{provider}/{org}/{name}": {
      "get": {
        "tags": [
          "Projects"
        ],
        "summary": "Get project by URL identifier",
        "description": "Get the latest summary for a specific project using the project's URL identifier `{provider}/{org}/{name}`.\n\nTo find the URL identifier for a project, view the project overview page in LGTM. The URL identifier follows after `/projects`. For example, for a project with the URL `https://lgtm.example.com/projects/g/apache/commons-io` the URL identifier is `g/apache/commons-io`. In the example, `g` represents the `provider` (repository host), `apache` is the `organization` [...]",
        "operationId": "getProjectByUrlIdentifier",
        "security": [
          {
            "access-token": [
              "projects:read"
            ]
          }
        ],
        "x-auth-mode": "BINARY"
      }
    },
    "/snapshots/{project-id}/{language}": {
      "get": {
        "tags": [
          "Snapshots"
        ],
        "summary": "Download a snapshot",
        "description": "Download a CodeQL database from LGTM, representing a snapshot of the codebase, to run queries in your IDE.\n\nThis endpoint works for projects that have been successfully analyzed for the language specified in the request.  A successful request redirects you to a URL for downloading a database that represents the code snapshot, as specified in the `Location:` header in the response. Therefore, your HTTP client should be configured to follow redirects. For example, if you [...]",
        "operationId": "getSnapshot",
        "security": [
          {
            "access-token": [
              "snapshots:read"
            ]
          }
        ],
        "x-auth-mode": "BINARY"
      },
      "post": {
        "tags": [
          "Snapshots"
        ],
        "summary": "Start snapshot upload session",
        "description": "Start a session to upload an externally-built database (which represents a snapshot of a codebase) to a project on LGTM. \n\nThis endpoint works for projects that are already on LGTM, and the selected language of  the database must already be configured. The project must be configured with 'upload' analysis mode. You can upload a \"bundled\" CodeQL database or a database exported by  the QL command-line tools (`odasa`).\n\nIf your database was generated using a version of[...]",
        "operationId": "initSnapshotUpload",
        "security": [
          {
            "access-token": [
              "snapshots:write"
            ]
          }
        ],
        "x-auth-mode": "BINARY"
      }
    },
    "/snapshots/uploads/{session-id}": {
      "put": {
        "tags": [
          "Snapshots"
        ],
        "summary": "Upload snapshot",
        "description": "Upload a database representing a snapshot of a codebase.  The database is sent in one or more parts. Each part is sent in the request body. \nUse the [`POST /snapshots/{project-id}/{language}`](https://lgtm.com/help/lgtm/api/api-v1#opIdinitSnapshotUpload) endpoint  to start an upload session before uploading a database part. Database parts must have been generated and prepared for upload using the CodeQL CLI or the QL command-line tools. For further information on exporti[...]",
        "operationId": "uploadPart",
        "security": [
          {
            "access-token": [
              "snapshots:write"
            ]
          }
        ],
        "x-auth-mode": "BINARY"
      },
      "post": {
        "tags": [
          "Snapshots"
        ],
        "summary": "Complete snapshot upload session",
        "description": "Completes the database upload by closing the upload session, upgrading the database if appropriate, and scheduling analysis of that snapshot of the codebase.\n\nYou can view the analysis progress and access the results using the `task-result-url`.\n",
        "operationId": "completeUpload",
        "security": [
          {
            "access-token": [
              "snapshots:write"
            ]
          }
        ],
        "x-auth-mode": "BINARY"
      },
      "delete": {
        "tags": [
          "Snapshots"
        ],
        "summary": "Abort database upload process",
        "description": "Aborts the specified upload session and deletes any uploaded parts. After the session is aborted it cannot be restarted.\nIf any part uploads are in progress when the session is aborted, their data may not be deleted. To ensure that uploaded parts are deleted correctly, you should only abort an upload session after all part uploads have completed.\n",
        "operationId": "abortUpload",
        "security": [
          {
            "access-token": [
              "snapshots:write"
            ]
          }
        ],
        "x-auth-mode": "BINARY"
      }
    },
    "/analyses/{project-id}": {
      "post": {
        "tags": [
          "Analyses"
        ],
        "summary": "Run analysis of a specific commit",
        "description": "Trigger the analysis of a specific commit to a project. If a previous attempt to analyze that commit failed, this triggers a fresh analysis.  This is supported for all LGTM projects, regardless of repository type or host. The commit must be available in the main repository, but can be on a branch that isn't tracked by LGTM. For both LGTM.com and LGTM Enterprise, you must include an access token with the `analyses:write` scope.\n\nWhen you request the analysis of a commit,[...]",
        "operationId": "requestAnalysis",
        "security": [
          {
            "access-token": [
              "analyses:write"
            ]
          }
        ],
        "x-auth-mode": "BINARY"
      }
    },
    "/analyses/{project-id}/commits/{commit-id}": {
      "get": {
        "tags": [
          "Analyses"
        ],
        "summary": "Get analysis summary for a specific commit",
        "description": "Get a summary of the analysis results for a specific commit, or the latest commit, to a project. (For projects configured for sparse or upload analysis, only `latest` is supported.) \n\nThis endpoint reports a summary of results for each language, and also the analysis identifier. You can use the analysis identifier to download full details of all the alerts  found by the analysis. For more information, see [Get detailed alert information](https://lgtm.com/help/lgtm/api/a[...]",
        "operationId": "getAnalysisForCommit",
        "security": [
          {
            "access-token": [
              "analyses:read"
            ]
          }
        ],
        "x-auth-mode": "BINARY"
      }
    },
    "/analyses/{analysis-id}": {
      "get": {
        "tags": [
          "Analyses"
        ],
        "summary": "Get analysis summary",
        "description": "Get a summary of the analysis results for a specific analysis identifier.\n\nTo find the analysis identifier for a commit, use the `/analyses/{project-id}/commits/{commit-id}` endpoint. For more information, see [Get analysis summary for a specific commit](https://lgtm.com/help/lgtm/api/api-v1#opIdgetAnalysisForCommit).\n\nThis endpoint reports the commit analyzed and a summary of the results for each language. Alternatively, you can use this identifier to download full d[...]",
        "operationId": "getAnalysis",
        "security": [
          {
            "access-token": [
              "analyses:read"
            ]
          }
        ],
        "x-auth-mode": "BINARY"
      }
    },
    "/analyses/{analysis-id}/alerts": {
      "get": {
        "tags": [
          "Analyses"
        ],
        "summary": "Get detailed alert information",
        "description": "Download all the alerts found by an analysis.\nUse the `Accept:` request header to specify the output media type as either CSV or [SARIF](https://lgtm.com/help/lgtm/sarif-results-file): \n\n- `application/sarif+json`: Alerts in SARIF format. If no version is specified the latest supported SARIF version is used.\n- `application/json`: Alerts in SARIF format (*deprecated*). \n  If no version is specified, [SARIF 2.0.0](http://docs.oasis-open.org/sarif/sarif/v2.0/sarif-v2.0.[...]",
        "operationId": "getAlerts",
        "security": [
          {
            "access-token": [
              "analyses:read"
            ]
          }
        ],
        "x-auth-mode": "BINARY"
      }
    },
    "/codereviews/{project-id}": {
      "post": {
        "tags": [
          "Code reviews"
        ],
        "summary": "Run code review for a patch",
        "description": "Trigger the code review of a patch. This is available for projects with Git repositories.\n\nYour request must include:\n\n  * Identifier for the base commit\n  * Patch generated using `git diff --binary` (see [git diff](https://git-scm.com/docs/git-diff))\n  * Header `Content-Type: application/octet-stream`\n  * For both LGTM.com and LGTM Enterprise, an access token with the `codereviews:write` scope\n\nNote that if you make a request using Curl, you'll also need to add [...]",
        "operationId": "requestReview",
        "security": [
          {
            "access-token": [
              "codereviews:write"
            ]
          }
        ],
        "x-auth-mode": "BINARY"
      }
    },
    "/codereviews/{review-id}": {
      "get": {
        "tags": [
          "Code reviews"
        ],
        "summary": "Get results of code review",
        "description": "Get the results of a code review using the review identifier for the task.\n\nWhen you request a code review, the response includes a task result URL of the form: `/codereviews/{review-id}`.\n\nThis endpoint reports the results of a complete code review, or the status of a review  that's still in progress.\n",
        "operationId": "getCodeReview",
        "security": [
          {
            "access-token": [
              "codereviews:read"
            ]
          }
        ],
        "x-auth-mode": "BINARY"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "access-token": {
        "type": "http",
        "description": "\n\nLGTM Enterprise users need to create and use an access token to authenticate with this API. This is optional for LGTM.com users unless they want to submit a CodeQL query for analysis of one or more projects, or to request the analysis of a patch or commit. LGTM.com users also need an access token to  check on the progress of long running tasks using the `/operations` endpoint.\nLog in to LGTM and use the **Create token** option in your Account settings page. For more [...]",
        "scheme": "bearer"
      }
    }
  }
}