#!/usr/bin/env bash

#
# Bootstraps a development environment.
#
# This includes:
# * install pre-commit hooks
# * setup content dependencies with poetry
# * Setup npm

function exit_on_error {
    if [ "${1}" -ne 0 ]; then
        echo "ERROR: ${2}, exiting with code ${1}" 1>&2
        exit "${1}"
    fi
}

# poetry is installed in ~/.local/bin
PATH=~/.local/bin:$PATH

if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
    cat << __EOF__
Setup development environment (run with no arguments):
* install pre-commit hooks (set NO_HOOKS=1 to skip)
__EOF__
    exit 0
fi

if [ ! "${PWD}" == "$(git rev-parse --show-toplevel)" ]; then
    cat >&2 <<__EOF__
ERROR: this script must be run at the root of the source tree
__EOF__
    exit 1
fi

HOOKS_DIR="${PWD}/.hooks"
GIT_HOOKS_DIR="${PWD}/.git/hooks"

if [ -n "${NO_HOOKS}" ]; then
    echo "Skipping hooks setup as environment variable NO_HOOKS is set"
else
    if [ ! -e "${GIT_HOOKS_DIR}/pre-commit" ]; then
        echo "Installing 'pre-commit' hooks"
        ln -s "${HOOKS_DIR}/pre-commit" "${GIT_HOOKS_DIR}/pre-commit"
        exit_on_error $? "Failed to install pre-commit hook"
    else
        echo "Skipping install of pre-commit hook as it already exists."
        echo "If you want to re-install: 'rm ${GIT_HOOKS_DIR}/pre-commit' and then run this script again."
        exit 1
    fi
fi

echo "======================="
if [ -z "${INSTALL_POETRY}" ]; then
    if ! command -v poetry >/dev/null 2>&1; then
        echo "ERROR: poetry is missing. Please run the following command to install poetry:
               curl -sSL https://install.python-poetry.org | python3 -" 1>&2
        exit 1
    fi
else
    should_install_poetry="yes"
    if command -v poetry >/dev/null 2>&1; then
        if [[ "$(poetry --version)" == "Poetry (version ${POETRY_VERSION})" ]]; then
            echo "Poetry already installed:$(poetry --version) with correct version"
            should_install_poetry="no"
        else
            echo "Poetry installed with a different version:$(poetry --version) required:${POETRY_VERSION}"
        fi
    else
        echo "Poetry isn't installed"
    fi
    if [[ "${should_install_poetry}" == "yes" ]]; then
        echo "Installing Poetry version:${POETRY_VERSION}"
        python3 .hooks/install.python-poetry.py --version "${POETRY_VERSION}"
        # curl -sSxL https://install.python-poetry.org | python3 - --version "${POETRY_VERSION}"
        error_code=$?
        if [ -n "${ARTIFACTS_FOLDER}" ] && [ "${error_code}" -ne 0 ]; then
            cp ${PWD}/poetry-installer-error-*.log "${ARTIFACTS_FOLDER}"
        fi
        if ! command -v poetry >/dev/null 2>&1; then
            exit_on_error $? "Poetry isn't installed"
        fi
        if [[ "$(poetry --version)" == "Poetry (version ${POETRY_VERSION})" ]]; then
          echo "Poetry version ${POETRY_VERSION} installed successfully"
        else
          exit_on_error 1 "Poetry version $(poetry --version) doesn't match the required version: ${POETRY_VERSION}"
        fi
        exit_on_error $error_code "Failed to install Poetry version:${POETRY_VERSION}"
    fi
fi

if [ -n "${CI}" ]; then
    echo "Detected CI environment"
    echo "Checking whether poetry files are valid"
    poetry check --no-interaction
    exit_on_error $? "Failed to check poetry files"
    echo "Installing dependencies..."
    poetry install --no-interaction
    exit_on_error "${exit_code}" "Failed to install dependencies"
else
    echo "Detected local environment"
    echo "Check if poetry files are valid"
    poetry check
    exit_on_error $? "Failed to check poetry files"
    echo "Installing dependencies..."
    poetry install
    exit_on_error $? "Failed to install dependencies"
fi

echo "=========================="
echo "Done setting up virtualenv with poetry"
echo "Activate the venv by running: poetry shell"
echo "Deactivate by running: deactivate"
echo "======================="

if [ -n "${CI}" ]; then
    echo "Detected CI environment. Running npm ci..."
    npm ci --cache .npm --prefer-offline --no-fund --no-audit  # Clean install
    exit_on_error $? "Failed to install npm dependencies"
elif [ -n "${NO_NPM}" ]; then
    echo "Skipping npm node modules setup as environment variable NO_NPM is set"
else
    if ! command -v npm >/dev/null 2>&1; then
            cat >&2 <<__EOF__
Skipping npm node modules as 'npm' command was not found!
node and npm are optional but recommended. We use node for validating README files.
You can install node and npm on your machine, and then run: 'npm install'
__EOF__
        exit 1
    else
        echo "Running: npm install ..."        
        npm install --no-fund --no-audit
        exit_on_error $? "Failed to install npm dependencies"
    fi
fi

echo "Finished setting up the environment."
exit 0
