# yaml-language-server: $schema=../../schema/configurations.schema.json
metadata:
  title: "Configuration"
  description: "Adjust and refine your configuration settings"
  help: |
    You can configure the following settings.  
    **Automation and& Remediation**:

    * **Allow creating users**, **Allow updating users**, **Allow enabling users**, and **Allow disabling users**: Toggle these specific user permissions on or off. You can also choose to automatically create a user if they are not found during an update command.  
    * **Default Locale SID Key:** Choose how dates, times, numbers, and currency are displayed throughout the application based on your geographic region. The default is en\_US.  
    * **Default Email Encoding Key**: Sets the standard used to display characters in your outgoing emails. This ensures that special characters, symbols, and different languages appear correctly for your recipients. The default is ISO-8859-1.  
    * **Integration Log Level**: Possible values are **Off** (default), **Debug**, and **Verbose**.

    **Security Posture**:

    * **Sync Interval**: Defines how often the system checks your cloud environment for security risks, misconfigurations, and compliance updates. More frequent syncs may impact API rate limits. The default is every 15 minutes.  
    * **Application Tag**: Assigns a category to your cloud resources based on their operational purpose. This helps you filter security alerts and apply different compliance policies to specific environments. The default is **None**.


configurations:
  - id: "automation-and-remediation"
    configurations:
      - fields:
          - id: "create_user_enabled"
            title: "Allow creating users"
            field_type: "checkbox"
            options:
              default_value: true
              create_modifiers:
                required: false
                hidden: false
              edit_modifiers:
                required: false
                hidden: false
          - id: "update_user_enabled"
            title: "Allow updating users"
            field_type: "checkbox"
            options:
              default_value: true
              create_modifiers:
                required: false
                hidden: false
              edit_modifiers:
                required: false
                hidden: false
          - id: "enable_user_enabled"
            title: "Allow enabling users"
            field_type: "checkbox"
            options:
              default_value: true
              create_modifiers:
                required: false
                hidden: false
              edit_modifiers:
                required: false
                hidden: false
          - id: "disable_user_enabled"
            title: "Allow disabling users"
            field_type: "checkbox"
            options:
              default_value: true
              create_modifiers:
                required: false
                hidden: false
              edit_modifiers:
                required: false
                hidden: false
      - fields:
          - id: "create_if_not_exists"
            title: "Automatically create user if not found"
            field_type: "switch"
            options:
              description: "Automatically create user if not found in update and enable commands"
              default_value: true
              create_modifiers:
                required: false
                hidden: false
              edit_modifiers:
                required: false
                hidden: false
      - fields:
          - id: "localesidkey"
            title: "Default Locale SID Key"
            field_type: "input"
            options:
              description: "Used when creating a new user"
              default_value: "en_US"
              create_modifiers:
                required: true
                hidden: false
              edit_modifiers:
                required: true
                hidden: false
      - fields:
          - id: "emailencodingkey"
            title: "Default Email Encoding Key"
            field_type: "input"
            options:
              description: "Used when creating a new user"
              default_value: "ISO-8859-1"
              create_modifiers:
                required: true
                hidden: false
              edit_modifiers:
                required: true
                hidden: false
      - fields:
          - id: "integrationLogLevel"
            title: "Integration Log Level"
            field_type: "select"
            metadata:
              xsoar:
                # This configuration is used in the backend and not exposed to content code.
                config_type: "backend" 
            options:
              description: "Set the log level for the integration"
              placeholder: "Select log level"
              default_value: "Off"
              values:
                - key: "Off"
                  label: "Off"
                - key: "Debug"
                  label: "Debug"
                - key: "Verbose"
                  label: "Verbose"
              create_modifiers:
                required: false
                hidden: false
              edit_modifiers:
                required: false
                hidden: false
            
  - id: "saas-posture-config-monitoring"
    configurations:
      - fields:
        - id: "sync_interval"
          title: "Sync Interval"
          field_type: "select"
          options:
            description: "How often to synchronize data from the SaaS provider"
            hint: "More frequent syncs may impact API rate limits."
            layout:
              cols: 3
            placeholder: "Select sync interval"
            default_value: "15"
            values:
              - key: "1440"
                label: "Every 24 hours"
              - key: "720"
                label: "Every 12 hours"
              - key: "480"
                label: "Every 8 hours"
              - key: "120"
                label: "Every 2 hours"
              - key: "60"
                label: "Every 1 hour"
              - key: "15"
                label: "Every 15 minutes"
            create_modifiers:
              required: true
              hidden: false
              read_only: false
            edit_modifiers:
              required: true
              hidden: false
              read_only: false
        - id: "application_tag"
          title: "Application Tag"
          field_type: "select"
          options:
            description: "Application Tenant Environment"
            hint: "Tag applications to distinguish between different types of environments."
            layout:
              cols: 3
            placeholder: "Select Application Tag"
            default_value: "none"
            values:
              - key: "none"
                label: "None"
              - key: "default"
                label: "Default"
              - key: "dev"
                label: "Dev"
              - key: "internal"
                label: "Internal"
              - key: "production"
                label: "Production"
              - key: "qa"
                label: "QA"
              - key: "sandbox"
                label: "Sandbox"
            create_modifiers:
              required: true
              hidden: false
              read_only: false
            edit_modifiers:
              required: true
              hidden: false
              read_only: false
