id: TestCloudflareWAFPlaybook
name: TestCloudflareWAFPlaybook
version: -1
fromversion: 6.2.0
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: baa498fe-0fc8-4e7a-a984-ce55a5fbf7dc
    type: start
    task:
      id: baa498fe-0fc8-4e7a-a984-ce55a5fbf7dc
      version: -1
      name: ''
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    view: '{"position":{"x":50,"y":50}}'
    note: false
    timertriggers: []
    ignoreworker: false
  '1':
    id: 1
    taskid: 83fb613a-e3b4-47ad-a876-bbcb3f626106
    type: regular
    task:
      id: 83fb613a-e3b4-47ad-a876-bbcb3f626106
      version: -1
      name: DeleteContext
      description: ''
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      all:
        simple: yes
    separatecontext: false
    view: '{"position":{"x":50,"y":200}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '2':
    id: 2
    taskid: f1b0a98e-cd11-4013-92ad-bbb59a741190
    type: regular
    task:
      id: f1b0a98e-cd11-4013-92ad-bbb59a741190
      version: -1
      name: cloudflare-waf-ruleset-create
      description: ''
      script: CloudflareWAF|||cloudflare-waf-ruleset-create
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '3'
    scriptarguments:
      name:
        simple: Test custom ruleset
      kind:
        simple: custom
      phase:
        simple: http_request_firewall_custom
    separatecontext: false
    view: '{"position":{"x":50,"y":400}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '3':
    id: '3'
    taskid: 9267bd1e-0e16-481d-b10f-5b6e18429fb6
    type: condition
    task:
      id: 9267bd1e-0e16-481d-b10f-5b6e18429fb6
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '4'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Ruleset.id
            iscontext: true
    view: '{"position":{"x":50,"y":600}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '4':
    id: 4
    taskid: 4fda198b-ea38-4196-9683-78bf229f1800
    type: regular
    task:
      id: 4fda198b-ea38-4196-9683-78bf229f1800
      version: -1
      name: cloudflare-waf-ruleset-rule-create
      description: ''
      script: CloudflareWAF|||cloudflare-waf-ruleset-rule-create
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '5'
    scriptarguments:
      ruleset_id:
        simple: ${CloudflareWAF.Ruleset.id}
      rule:
        simple: '{"action": "block", "expression": "(ip.src eq 192.0.2.1)", "description": "Block bad IP"}'
    separatecontext: false
    view: '{"position":{"x":50,"y":800}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '5':
    id: '5'
    taskid: 5076c236-f62c-42d2-9c86-0d1add1a5b7b
    type: condition
    task:
      id: 5076c236-f62c-42d2-9c86-0d1add1a5b7b
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '6'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Ruleset.rules.id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Ruleset.rules.action
            iscontext: true
    view: '{"position":{"x":50,"y":1000}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '6':
    id: 6
    taskid: 040094c4-76c1-4e25-9213-7f0515be0cec
    type: regular
    task:
      id: 040094c4-76c1-4e25-9213-7f0515be0cec
      version: -1
      name: cloudflare-waf-ruleset-rule-update
      description: ''
      script: CloudflareWAF|||cloudflare-waf-ruleset-rule-update
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '7'
    scriptarguments:
      ruleset_id:
        simple: ${CloudflareWAF.Ruleset.id}
      rule_id:
        simple: ${CloudflareWAF.Ruleset.rules.id}
      rule:
        simple: '{"action": "log", "expression": "(ip.src eq 192.0.2.1)", "description": "Log bad IP"}'
    separatecontext: false
    view: '{"position":{"x":50,"y":1200}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '7':
    id: 7
    taskid: 57f8dc48-b353-4cbe-a987-81e25755fca5
    type: regular
    task:
      id: 57f8dc48-b353-4cbe-a987-81e25755fca5
      version: -1
      name: cloudflare-waf-ruleset-version-list
      description: ''
      script: CloudflareWAF|||cloudflare-waf-ruleset-version-list
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '8'
    scriptarguments:
      ruleset_id:
        simple: ${CloudflareWAF.Ruleset.id}
    separatecontext: false
    view: '{"position":{"x":50,"y":1400}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '8':
    id: '8'
    taskid: f8073163-9a26-4df5-b6a5-a1f061d31123
    type: condition
    task:
      id: f8073163-9a26-4df5-b6a5-a1f061d31123
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '9'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Ruleset.version
            iscontext: true
    view: '{"position":{"x":50,"y":1600}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '9':
    id: 9
    taskid: fc74c090-a714-4575-a45c-ee33c999b4c1
    type: regular
    task:
      id: fc74c090-a714-4575-a45c-ee33c999b4c1
      version: -1
      name: cloudflare-waf-ruleset-rule-delete
      description: ''
      script: CloudflareWAF|||cloudflare-waf-ruleset-rule-delete
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '10'
    scriptarguments:
      ruleset_id:
        simple: ${CloudflareWAF.Ruleset.id}
      rule_id:
        simple: ${CloudflareWAF.Ruleset.rules.id}
    separatecontext: false
    view: '{"position":{"x":50,"y":1800}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '10':
    id: 10
    taskid: 5f220d88-7a9d-48b2-92c4-bf21450e45ce
    type: regular
    task:
      id: 5f220d88-7a9d-48b2-92c4-bf21450e45ce
      version: -1
      name: cloudflare-waf-ruleset-delete
      description: ''
      script: CloudflareWAF|||cloudflare-waf-ruleset-delete
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '14'
    scriptarguments:
      ruleset_id:
        simple: ${CloudflareWAF.Ruleset.id}
    separatecontext: false
    view: '{"position":{"x":50,"y":2000}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '14':
    id: 14
    taskid: 6fe2a2ea-f116-45c7-82c5-3f0249ee8384
    type: regular
    task:
      id: 6fe2a2ea-f116-45c7-82c5-3f0249ee8384
      version: -1
      name: cloudflare-waf-zone-list
      description: ''
      script: CloudflareWAF|||cloudflare-waf-zone-list
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '15'
    scriptarguments: {}
    separatecontext: false
    view: '{"position":{"x":50,"y":2200}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '15':
    id: '15'
    taskid: 6097e316-5e2f-45d2-b139-85460c84741a
    type: condition
    task:
      id: 6097e316-5e2f-45d2-b139-85460c84741a
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '16'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isExists
          left:
            value:
              simple: CloudflareWAF.Zone.success
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Zone.id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Zone.name
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Zone.development_mode
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Zone.original_name_servers
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Zone.original_registrar
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Zone.original_dnshost
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Zone.created_on
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Zone.modified_on
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Zone.activated_on
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Zone.status
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: CloudflareWAF.Zone.paused
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Zone.type
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Zone.permissions
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Zone.Account
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Zone.owner
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.Zone.name_servers
            iscontext: true
    view: '{"position":{"x":50,"y":2400}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '16':
    id: 16
    taskid: 38070daf-5047-4a0e-b65e-3bb05ea7ee71
    type: regular
    task:
      id: 38070daf-5047-4a0e-b65e-3bb05ea7ee71
      version: -1
      name: cloudflare-waf-ip-list-create
      description: ''
      script: CloudflareWAF|||cloudflare-waf-ip-list-create
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '17'
    scriptarguments: {}
    separatecontext: false
    view: '{"position":{"x":50,"y":2600}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '17':
    id: '17'
    taskid: af4b4897-0bfe-426f-af96-4daa718af8cf
    type: condition
    task:
      id: af4b4897-0bfe-426f-af96-4daa718af8cf
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '18'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.IpList.id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.IpList.name
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.IpList.description
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.IpList.kind
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.IpList.num_items
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.IpList.num_referencing_filters
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.IpList.created_on
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.IpList.modified_on
            iscontext: true
    view: '{"position":{"x":50,"y":2800}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '18':
    id: 18
    taskid: 526cfddb-cf83-4929-833b-fdb1a40b23a5
    type: regular
    task:
      id: 526cfddb-cf83-4929-833b-fdb1a40b23a5
      version: -1
      name: cloudflare-waf-ip-list-delete
      description: ''
      script: CloudflareWAF|||cloudflare-waf-ip-list-delete
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '19'
    scriptarguments: {}
    separatecontext: false
    view: '{"position":{"x":50,"y":3000}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '19':
    id: 19
    taskid: eab556e2-7e63-495a-acd6-81de40401482
    type: regular
    task:
      id: eab556e2-7e63-495a-acd6-81de40401482
      version: -1
      name: cloudflare-waf-ip-lists-list
      description: ''
      script: CloudflareWAF|||cloudflare-waf-ip-lists-list
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '20'
    scriptarguments: {}
    separatecontext: false
    view: '{"position":{"x":50,"y":3200}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '20':
    id: '20'
    taskid: 2da8746c-77c3-4b58-b04b-0938e74f52f0
    type: condition
    task:
      id: 2da8746c-77c3-4b58-b04b-0938e74f52f0
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '21'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.IpList.id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.IpList.name
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.IpList.description
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.IpList.kind
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.IpList.num_items
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.IpList.num_referencing_filters
            iscontext: true
    view: '{"position":{"x":50,"y":3400}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '21':
    id: 21
    taskid: 5e5d349c-bede-4472-a872-879101fdeaeb
    type: regular
    task:
      id: 5e5d349c-bede-4472-a872-879101fdeaeb
      version: -1
      name: cloudflare-waf-ip-list-item-create
      description: ''
      script: CloudflareWAF|||cloudflare-waf-ip-list-item-create
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '22'
    scriptarguments: {}
    separatecontext: false
    view: '{"position":{"x":50,"y":3600}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '22':
    id: 22
    taskid: 88778b5e-d43a-4258-a9a7-941414e4731c
    type: regular
    task:
      id: 88778b5e-d43a-4258-a9a7-941414e4731c
      version: -1
      name: cloudflare-waf-ip-list-item-update
      description: ''
      script: CloudflareWAF|||cloudflare-waf-ip-list-item-update
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '23'
    scriptarguments: {}
    separatecontext: false
    view: '{"position":{"x":50,"y":3800}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '23':
    id: 23
    taskid: 709fff7a-23ce-4c00-971b-e6edfb09fbd0
    type: regular
    task:
      id: 709fff7a-23ce-4c00-971b-e6edfb09fbd0
      version: -1
      name: cloudflare-waf-ip-list-item-delete
      description: ''
      script: CloudflareWAF|||cloudflare-waf-ip-list-item-delete
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '24'
    scriptarguments: {}
    separatecontext: false
    view: '{"position":{"x":50,"y":4000}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '24':
    id: 24
    taskid: 7d735014-7c45-4bde-8deb-5abbee8e8fc0
    type: regular
    task:
      id: 7d735014-7c45-4bde-8deb-5abbee8e8fc0
      version: -1
      name: cloudflare-waf-ip-list-item-list
      description: ''
      script: CloudflareWAF|||cloudflare-waf-ip-list-item-list
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '25'
    scriptarguments: {}
    separatecontext: false
    view: '{"position":{"x":50,"y":4200}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '25':
    id: '25'
    taskid: 1253366c-cfe8-42b3-bae8-6b533feb62e7
    type: condition
    task:
      id: 1253366c-cfe8-42b3-bae8-6b533feb62e7
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '26'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.IpListItem.items
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CloudflareWAF.IpListItem.list_id
            iscontext: true
    view: '{"position":{"x":50,"y":4400}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '26':
    id: '26'
    taskid: 7b8a3500-07da-452a-a75a-95af4fd2c047
    type: title
    task:
      id: 7b8a3500-07da-452a-a75a-95af4fd2c047
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ''
      description: ''
    separatecontext: false
    view: '{"position":{"x":50,"y":4600}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
view: '{"linkLabelsPosition":{},"paper":{"dimensions":{"height":200,"width":380,"x":50,"y":50}}}'
inputs: []
outputs: []
description: ''
