id: Taegis XDR Case Playbook
fromversion: 5.0.0
version: 3
contentitemexportablefields:
  contentitemfields:
    packID: ""
    packName: Default
    itemVersion: 2.0.16
    fromServerVersion: 5.0.0
    toServerVersion: ""
    definitionid: ""
    prevname: ""
vcShouldKeepItemLegacyProdMachine: false
name: Taegis XDR Case Playbook
description: Abbreviated triage playbook for Taegis XDR cases. Assigns an analyst, prompts manual review, and optionally closes the investigation.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 08854949-08a5-4873-8f01-b3935c78675f
    type: start
    task:
      id: 08854949-08a5-4873-8f01-b3935c78675f
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 4a2366db-81b0-41b5-8c8f-41b09e83a215
    type: condition
    task:
      id: 4a2366db-81b0-41b5-8c8f-41b09e83a215
      version: -1
      name: Manually review the incident.
      description: Manually review and investigate this incident.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "No":
      - "12"
      "Yes":
      - "8"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 9ed78579-2deb-4871-8c5c-f6118f6e1ac2
    type: regular
    task:
      id: 9ed78579-2deb-4871-8c5c-f6118f6e1ac2
      version: -1
      name: Close Investigation
      description: Closes the current incident.
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      closeNotes:
        simple: Default Enrichment Playbook
    reputationcalc: 1
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: de6f9320-320d-4bd6-820f-b612a7a0c2c7
    type: title
    task:
      id: de6f9320-320d-4bd6-820f-b612a7a0c2c7
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "7_12_No": 0.65,
      "7_8_Yes": 0.71
    },
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
sourceplaybookid: playbook0
