import sys
import argparse
import urllib3
from github import Github
from github.Repository import Repository
from github.PullRequest import PullRequest
from utils import timestamped_print

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
print = timestamped_print

SKIP_LABEL = "skip-ai-review"
BOT_USERNAME = "content-bot"
REQUIRED_TEXT = "please review and approve the results generated by the AI Reviewer by responding 👍 on this comment."
REPO = "demisto/content"


def arguments_handler():
    """Validates and parses script arguments.

    Returns:
       Namespace: Parsed arguments object.
    """
    parser = argparse.ArgumentParser(description="Check if AI review is approved.")
    parser.add_argument("-p", "--pr_number", help="The PR number to check.")
    parser.add_argument("-g", "--github_token", help="The GitHub token to authenticate the GitHub client.")
    return parser.parse_args()


def main():
    """
    This script checks if the AI review has been approved by a human reviewer.
    It passes if:
    1. The PR has the 'skip-ai-review' label.
    2. OR there is a comment from 'content-bot' with the required text AND a '+1' reaction.
    """
    options = arguments_handler()
    pr_number = options.pr_number
    github_token = options.github_token

    github_client: Github = Github(github_token, verify=False)
    content_repo: Repository = github_client.get_repo(REPO)
    pr: PullRequest = content_repo.get_pull(int(pr_number))

    # 1. Check for Bypass Label
    pr_label_names = [label.name for label in pr.labels]
    if SKIP_LABEL in pr_label_names:
        print(f'✅ Found "{SKIP_LABEL}" label. Skipping AI review check.')
        sys.exit(0)

    print(f"Checking for AI review approval in PR {pr_number}...")

    # 2. Verify content-bot's comment existance and review approval.
    comments = pr.get_reviews()
    found_bot_comment = False

    for comment in comments:
        print(comment.body)
        # Check if comment is from the bot and has the required text
        if (comment.user.login == BOT_USERNAME) and (REQUIRED_TEXT in comment.body):
            found_bot_comment = True
            print(f"Found AI Review comment (ID: {comment.id}). Checking reactions...")

    if not found_bot_comment:
        print("⚠️ No AI Review comment found from content-bot.")

    print(
        "❌ AI Review check failed. Please trigger an AI review, check if the generated comments valid and relevant ",
        "otherwise edit or delete them) and finally approve the results with a 👍 reaction.",
    )
    sys.exit(1)


if __name__ == "__main__":
    main()
