import sys
import argparse
from github import Github, Auth
from github.PullRequest import PullRequest
from github.PullRequestReview import PullRequestReview
import requests
import urllib3
from utils import timestamped_print

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
print = timestamped_print

SKIP_LABEL = "skip-ai-review"
BOT_USERNAME = "content-bot"
REQUIRED_TEXT = "please review and approve the results generated by the AI Reviewer by responding 👍 on this comment."
ORG_NAME = "demisto"
REPO_NAME = "content"
PERMITTED_TEAMS = ["content-ai-reviewer-developers", "tech writers"]
CONTRIB_BRANCH_PREFIX = "contrib/"


def arguments_handler():
    """Validates and parses script arguments.
    Return
        Namespace: Parsed arguments object.
    """
    parser = argparse.ArgumentParser(description="Check if AI review is approved.")
    parser.add_argument("-p", "--pr_number", help="The PR number to check.")
    parser.add_argument("-g", "--github_token", help="The GitHub token to authenticate the GitHub client.")
    return parser.parse_args()


def get_reactions_query() -> str:
    """Returns the GraphQL query to fetch reactions for a specific Node ID."""
    return """
    query($nodeId: ID!) {
      node(id: $nodeId) {
        ... on PullRequestReview {
          reactions(first: 20) {
            nodes {
              content
              user { login }
            }
          }
        }
      }
    }
    """


def is_minimized_query() -> str:
    """
    Returns the GraphQL query to fetch minimization status.
    We use '... on Comment' because both IssueComment and
    PullRequestReviewComment implement the Comment interface.
    """
    return """
        query($nodeId: ID!) {
        node(id: $nodeId) {
            ... on PullRequestReview {
            isMinimized
            minimizedReason
            }
        }
        }
        """


def fetch_reactions_via_graphql(node_id: str, token: str) -> list:
    """
    Uses GraphQL to fetch reactions for a specific GitHub Node ID (the review).
    This allows us to get the specific reaction content (THUMBS_UP) reliably.
    """
    url = "https://api.github.com/graphql"
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }
    variables = {"nodeId": node_id}

    try:
        response = requests.post(
            url, json={"query": get_reactions_query(), "variables": variables}, headers=headers, verify=False
        )
        response.raise_for_status()
        data = response.json()

        reactions = data.get("data", {}).get("node", {}).get("reactions", {}).get("nodes", [])
        return reactions
    except Exception as e:
        print(f"⚠️ GraphQL Request Failed for node {node_id}: {e}")
        return []


def is_minimized_via_graphql(node_id: str, token: str) -> bool:
    """
    Uses GraphQL to understand if a review is minimized or not.
    """
    url = "https://api.github.com/graphql"
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }
    variables = {"nodeId": node_id}

    try:
        response = requests.post(url, json={"query": is_minimized_query(), "variables": variables}, headers=headers, verify=False)
        response.raise_for_status()
        data = response.json()
        node_data = data.get("data", {}).get("node")

        return node_data and node_data.get("isMinimized")
    except Exception as e:
        print(f"⚠️ GraphQL Request Failed for node {node_id}: {e}")
        return False


def find_reaction_on_review(reviews: list[PullRequestReview], github_token: str, pr_number: str):
    if not reviews:
        return False, False

    print(f"Found {len(reviews)} AI review(s) from '{BOT_USERNAME}'. Checking for approvals...")

    for review in reviews:
        print(
            f"Found Bot Review (Node ID: {review.raw_data['node_id']}, Review ID: {review.id}). Checking reactions via GraphQL..."
        )
        reactions = fetch_reactions_via_graphql(review.raw_data["node_id"], github_token)

        thumb_up_found = False
        for reaction in reactions:
            if reaction.get("content") == "THUMBS_UP":
                user = reaction.get("user", {}).get("login")
                print(f"Found 👍 reaction from user: {user}")
                thumb_up_found = True
                break

        if not thumb_up_found:
            review_link = f"https://github.com/demisto/content/pull/{pr_number}#pullrequestreview-{review.id}"
            print(f"❌ No 👍 reaction found for review: {review_link}")
            return True, False

    return True, True


def is_user_in_permitted_team(github_client: Github, username: str) -> bool:
    """
    Check if a user is a member of the content-ai-reviewer-developers team.

    Args:
        github_client: The authenticated GitHub client.
        username: The GitHub username to check.

    Returns:
        True if the user is a member of the permitted team, False otherwise.
    """
    try:
        org = github_client.get_organization(ORG_NAME)
        for permitted_team in PERMITTED_TEAMS:
            team = org.get_team_by_slug(permitted_team)
            user = github_client.get_user(username)
            if team.has_in_members(user):
                return True
    except Exception as e:
        print(f"Error checking team membership for {username}: {e}")
        return False


def was_skip_label_added_by_authorized_user(pr: PullRequest, github_client: Github) -> tuple[bool, str]:
    """
    Check if the skip-ai-review label was added by a member of the permitted team.

    Args:
        pr: The pull request to check.
        github_client: The authenticated GitHub client.

    Returns:
        Tuple of (True, username) if the label was added by a permitted user,
        (False, "") otherwise.
    """
    for event in pr.get_issue_events():
        if event.event == "labeled" and event.label.name == SKIP_LABEL:
            actor_login = event.actor.login
            if is_user_in_permitted_team(github_client, actor_login):
                return True, actor_login
    return False, ""


def is_contrib_branch_by_content_bot(pr: PullRequest) -> bool:
    """
    Check if the PR is from a contrib branch and authored by content-bot.

    Args:
        pr: The pull request to check.

    Returns:
        True if the PR head branch starts with contrib/ and author is content-bot.
    """
    return pr.head.ref.startswith(CONTRIB_BRANCH_PREFIX) and pr.user.login == BOT_USERNAME


def should_bypass_check(github_client: Github, pr: PullRequest) -> bool:
    """
    Check for Bypass Label with proper authorization.

    Determines if the AI review check should be bypassed based on:
    1. The PR has a 'skip-ai-review' label AND is from a contrib/* branch authored by content-bot.
    2. OR the 'skip-ai-review' label was added by a member of the permitted team.

    Args:
        github_client (Github): The authenticated GitHub client used to check team membership.
        pr (PullRequest): The pull request to check for bypass conditions.

    Returns:
        bool: True if the AI review check should be bypassed, False otherwise.
    """
    current_labels = [label.name for label in pr.get_labels()]
    if SKIP_LABEL in current_labels:
        if is_contrib_branch_by_content_bot(pr):
            print(f'✅ Found "{SKIP_LABEL}" label on contrib branch PR by {BOT_USERNAME}. Skipping AI review check.')
            return True

        # Check if the label was added by an authorized team member
        is_authorized, added_by = was_skip_label_added_by_authorized_user(pr, github_client)
        if is_authorized:
            print(
                f'✅ Found "{SKIP_LABEL}" label added by {added_by} (member of {" or ".join(PERMITTED_TEAMS)}). '
                'Skipping AI review check.'
            )
            return True

        # Label exists but not authorized
        print(
            f'⚠️ Found "{SKIP_LABEL}" label, but it was not added by a member of {" or ".join(PERMITTED_TEAMS)}. Ignoring label.'
        )
    return False


def main():
    """
    This script checks if the AI review has been executed and approved by a human reviewer or intentionally bypassed.
    """
    options = arguments_handler()
    pr_number = options.pr_number
    github_token = options.github_token
    print(f"Checking PR {pr_number}")

    auth = Auth.Token(github_token)
    github_client = Github(auth=auth, verify=False)
    repo = github_client.get_repo(f"{ORG_NAME}/{REPO_NAME}")
    pr = repo.get_pull(int(pr_number))

    if should_bypass_check(github_client, pr):
        sys.exit(0)

    print("Fetching reviews...")
    reviews = pr.get_reviews()

    relevant_reviews: list[PullRequestReview] = [
        review
        for review in reviews
        if (
            review.user
            and review.user.login == BOT_USERNAME
            and REQUIRED_TEXT in review.body
            and not is_minimized_via_graphql(review.raw_data["node_id"], github_token)
        )
    ]

    found_reviews, all_approved = find_reaction_on_review(relevant_reviews, github_token, pr_number)

    if not found_reviews:
        print("❌ AI Review check failed. No AI Review comment found.")
        sys.exit(1)

    if not all_approved:
        print("❌ Not all AI reviews were approved with a 👍 reaction.")
        sys.exit(1)

    print("✅ All AI Reviews approved.")
    sys.exit(0)


if __name__ == "__main__":
    main()
