variables:
  CURRENT_BRANCH_NAME: "unified-connectors-content-integration"

include:
  - file: "/.gitlab/ci/content-ci/ci/.gitlab-ci.yml"
    ref: "unified-connectors-content-integration"
    project: "${CI_PROJECT_NAMESPACE}/infra"
