variables:
  CURRENT_BRANCH_NAME: "new-SC110-dependson-wrapper-scripts"

include:
  - file: "/.gitlab/ci/content-ci/ci/.gitlab-ci.yml"
    ref: "new-SC110-dependson-wrapper-scripts"
    project: "${CI_PROJECT_NAMESPACE}/infra"
