#!/usr/bin/expect -f

set timeout -1
spawn bash installer.sh
match_max 100000
expect -exact "1. ACKNOWLEDGMENT AND ACCEPTANCE\r"
send -- ":"
expect -exact ":"
send -- "q"
expect -exact "Do you accept the terms of the End User License Agreement? \[yes no\] "
send -- "yes\r"
expect -exact "Is this ok \[y/d/N\]: "
send -- "y\r"
expect -exact "Server HTTPS Port:  (default: '443') "
send -- "\r"
expect -exact "Enter name for admin user:  (default: 'admin') "
send -- "\r"
expect -exact "Enter password for user 'admin': "
<PASSWORD>
send -- "\r"
expect -exact "Verify password: "
<PASSWORD>
send -- "\r"
expect -exact "Otherwise, hit enter. "
send -- "\r"
expect -exact "Is this configuration OK? \[yes no\] "
send -- "yes\r"
expect -exact "Start the server? \[yes no\] "
send -- "yes\r"
expect -exact "Finished Successfully."
expect eof